// 节点注册表(由 React 版 nodes/registry.ts 移植)
library;

import 'data.dart';
import 'exec.dart';

Socket s(String id, String name, SocketType type, {bool? multi}) =>
    Socket(id: id, name: name, type: type, multi: multi);

ParamSpec param({
  required String key,
  required String label,
  required String type,
  dynamic defaultValue,
  List<Map<String, String>>? options,
  double? min,
  double? max,
  double? step,
  String? placeholder,
  String? help,
  bool? expose,
  String? action,
}) => ParamSpec(
  key: key,
  label: label,
  type: type,
  defaultValue: defaultValue,
  options: options,
  min: min,
  max: max,
  step: step,
  placeholder: placeholder,
  help: help,
  expose: expose,
  action: action,
);

const List<Map<String, String>> kFontOptions = [
  {'value': 'sans-serif', 'label': '默认 (sans-serif)'},
  {'value': 'Microsoft YaHei', 'label': '微软雅黑'},
  {'value': 'SimSun', 'label': '宋体'},
  {'value': 'SimHei', 'label': '黑体'},
  {'value': 'KaiTi', 'label': '楷体'},
  {'value': 'monospace', 'label': '等宽 (monospace)'},
  {'value': 'Courier New', 'label': 'Courier New'},
];

const List<Map<String, String>> kShapeOptions = [
  {'value': 'circle', 'label': '圆形'},
  {'value': 'square', 'label': '方形'},
  {'value': 'diamond', 'label': '菱形'},
  {'value': 'triangle', 'label': '三角形'},
];

/// 图表图元叠加输入口(点/线/面/文本,均可多连):各可视化节点共用。
/// 接入的图元像"原理化输出"一样直接绘制进图中(见 viewer.dart 图元叠加渲染)。
final List<Socket> kOverlaySockets = [
  Socket(
    id: 'in_pts',
    name: '点(散点·可多连)',
    type: SocketType.scatter,
    multi: true,
  ),
  Socket(
    id: 'in_lines',
    name: '线(曲线·可多连)',
    type: SocketType.series,
    multi: true,
  ),
  Socket(id: 'in_faces', name: '面(网格·可多连)', type: SocketType.mesh, multi: true),
  Socket(id: 'in_texts', name: '文本(可多连)', type: SocketType.text, multi: true),
];

final List<NodeConfig> kNodeConfigs = [
  // ================= 组输入节点 =================
  NodeConfig(
    id: 'table_input',
    label: '表格输入',
    category: Category.input,
    description: '输入表格数据:支持内置预设(火山图/销售/鸢尾花/物理曲线),或粘贴 CSV/TSV,或从文件导入。',
    inputs: [],
    outputs: [s('out0', '表格', SocketType.table)],
    params: [
      param(
        key: 'preset',
        label: '数据预设',
        type: 'select',
        defaultValue: 'volcano',
        options: [
          {'value': 'volcano', 'label': '火山图数据(基因表达)'},
          {'value': 'sales', 'label': '销售数据'},
          {'value': 'iris', 'label': '鸢尾花数据'},
          {'value': 'phys', 'label': '物理曲线(带噪声)'},
        ],
      ),
      param(
        key: 'mode',
        label: '数据来源',
        type: 'select',
        defaultValue: 'preset',
        options: [
          {'value': 'preset', 'label': '使用预设'},
          {'value': 'manual', 'label': '手动数据'},
        ],
      ),
      param(
        key: 'delimiter',
        label: '分隔符',
        type: 'select',
        defaultValue: 'csv',
        options: [
          {'value': 'csv', 'label': '逗号 ,'},
          {'value': 'tsv', 'label': '制表符 Tab'},
        ],
      ),
      param(
        key: 'dataText',
        label: '数据文本',
        type: 'textarea',
        defaultValue: '',
        placeholder: '每行一条记录,首行可为列名\nx,y\n1,2.5\n2,3.1\n...',
      ),
      param(
        key: 'import',
        label: '从 CSV/Excel 文件导入',
        type: 'button',
        defaultValue: null,
        action: 'import-csv',
      ),
    ],
    exec: kExec['table_input'],
  ),
  NodeConfig(
    id: 'axis_input',
    label: '坐标系输入',
    category: Category.input,
    description:
        '定义一个坐标系:维度(2D/3D)、各轴厘米长度、X/Y 起止数字、坐标轴定位方式(以原点为中心/总贴左边沿)。支持预设类型、各轴独立颜色/粗细(厘米)/网格开关、文字样式与导出像素大小。刻度数量按像素密度自动确定并标注数字。',
    inputs: [],
    outputs: [s('out0', '坐标系', SocketType.axes)],
    params: [
      param(key: 'name', label: '坐标系名称', type: 'text', defaultValue: '坐标系'),
      param(
        key: 'dim',
        label: '维度',
        type: 'select',
        defaultValue: '3d',
        options: [
          {'value': '3d', 'label': '三维 (X, Y, Z)'},
          {'value': '2d', 'label': '二维 (X, Y)'},
        ],
      ),
      param(
        key: 'axisPreset',
        label: '坐标系预设',
        type: 'select',
        defaultValue: 'default',
        options: [
          {'value': 'default', 'label': '默认'},
          {'value': 'math', 'label': '数学(细黑轴)'},
          {'value': 'engineering', 'label': '工程(彩色三轴)'},
          {'value': 'minimal', 'label': '极简(无网格)'},
          {'value': 'borderless', 'label': '无边框'},
        ],
        help: '预设提供基础轴样式;下方单独调整的颜色/粗细/网格,只要与"默认"预设不同即会覆盖预设值',
      ),
      param(
        key: 'xLen',
        label: 'X 轴长度(厘米)',
        type: 'number',
        defaultValue: 16,
        step: 0.5,
        min: 1,
      ),
      param(
        key: 'yLen',
        label: 'Y 轴长度(厘米)',
        type: 'number',
        defaultValue: 10,
        step: 0.5,
        min: 1,
      ),
      param(
        key: 'zLen',
        label: 'Z 轴长度(厘米,3D)',
        type: 'number',
        defaultValue: 8,
        step: 0.5,
        min: 1,
      ),
      param(
        key: 'xStart',
        label: 'X 起始数字',
        type: 'number',
        defaultValue: 0,
        step: 0.1,
      ),
      param(
        key: 'xEnd',
        label: 'X 结束数字',
        type: 'number',
        defaultValue: 10,
        step: 0.1,
      ),
      param(
        key: 'yStart',
        label: 'Y 起始数字',
        type: 'number',
        defaultValue: 0,
        step: 0.1,
      ),
      param(
        key: 'yEnd',
        label: 'Y 结束数字',
        type: 'number',
        defaultValue: 10,
        step: 0.1,
      ),
      param(
        key: 'zStart',
        label: 'Z 起始数字(3D)',
        type: 'number',
        defaultValue: -5,
        step: 0.1,
      ),
      param(
        key: 'zEnd',
        label: 'Z 结束数字(3D)',
        type: 'number',
        defaultValue: 5,
        step: 0.1,
      ),
      param(
        key: 'axisOrigin',
        label: '坐标轴位置',
        type: 'select',
        defaultValue: 'origin',
        options: [
          {'value': 'origin', 'label': '以原点为中心(有原点过原点,否则贴边)'},
          {'value': 'left', 'label': '总贴左边沿'},
        ],
      ),
      param(
        key: 'showBorder',
        label: '显示边界边框',
        type: 'boolean',
        defaultValue: true,
      ),
      param(
        key: 'grid',
        label: '显示网格(总开关)',
        type: 'boolean',
        defaultValue: true,
      ),
      param(
        key: 'axisColorX',
        label: 'X 轴颜色',
        type: 'color',
        defaultValue: '#333333',
      ),
      param(
        key: 'axisColorY',
        label: 'Y 轴颜色',
        type: 'color',
        defaultValue: '#333333',
      ),
      param(
        key: 'axisColorZ',
        label: 'Z 轴颜色(3D)',
        type: 'color',
        defaultValue: '#333333',
      ),
      param(
        key: 'axisWidthX',
        label: 'X 轴粗细(厘米)',
        type: 'number',
        defaultValue: 0.12,
        step: 0.02,
        min: 0.02,
        max: 1,
      ),
      param(
        key: 'axisWidthY',
        label: 'Y 轴粗细(厘米)',
        type: 'number',
        defaultValue: 0.12,
        step: 0.02,
        min: 0.02,
        max: 1,
      ),
      param(
        key: 'axisWidthZ',
        label: 'Z 轴粗细(厘米,3D)',
        type: 'number',
        defaultValue: 0.12,
        step: 0.02,
        min: 0.02,
        max: 1,
      ),
      param(
        key: 'gridX',
        label: 'X 方向网格线',
        type: 'boolean',
        defaultValue: true,
      ),
      param(
        key: 'gridY',
        label: 'Y 方向网格线',
        type: 'boolean',
        defaultValue: true,
      ),
      param(
        key: 'gridZ',
        label: 'Z 方向网格线(3D)',
        type: 'boolean',
        defaultValue: true,
      ),
      param(
        key: 'fontSize',
        label: '文字大小(px)',
        type: 'number',
        defaultValue: 10,
        step: 1,
        min: 6,
        max: 24,
      ),
      param(
        key: 'fontFamily',
        label: '字体',
        type: 'select',
        defaultValue: 'sans-serif',
        options: kFontOptions,
      ),
      param(key: 'labelX', label: 'X 轴标签', type: 'text', defaultValue: 'X'),
      param(key: 'labelY', label: 'Y 轴标签', type: 'text', defaultValue: 'Y'),
      param(key: 'labelZ', label: 'Z 轴标签(3D)', type: 'text', defaultValue: 'Z'),
      param(
        key: 'arrowX',
        label: 'X 轴箭头',
        type: 'boolean',
        defaultValue: true,
        help: '在 X 轴末端绘制箭头',
      ),
      param(
        key: 'arrowY',
        label: 'Y 轴箭头',
        type: 'boolean',
        defaultValue: true,
        help: '在 Y 轴末端绘制箭头',
      ),
      param(
        key: 'rotX',
        label: '旋转 X(度)',
        type: 'range',
        defaultValue: -20,
        min: -180,
        max: 180,
        step: 1,
        help: '原理化输出中的 3D 视角旋转(绕 X 轴,度)',
      ),
      param(
        key: 'rotY',
        label: '旋转 Y(度)',
        type: 'range',
        defaultValue: 25,
        min: -180,
        max: 180,
        step: 1,
        help: '原理化输出中的 3D 视角旋转(绕 Y 轴,度)',
      ),
      param(
        key: 'rotZ',
        label: '旋转 Z(度)',
        type: 'range',
        defaultValue: 0,
        min: -180,
        max: 180,
        step: 1,
        help: '原理化输出中的 3D 视角旋转(绕 Z 轴,度)',
      ),
    ],
    exec: kExec['axis_input'],
  ),
  NodeConfig(
    id: 'text_input',
    label: '文本输入',
    category: Category.input,
    description:
        '定义一个文本图元:内容、文本大小(厘米)、在坐标轴盒内的位置、背景色/文字颜色与字体。接入"原理化输出"后按厘米比例绘制。',
    inputs: [],
    outputs: [s('out0', '文本', SocketType.text)],
    params: [
      param(
        key: 'text',
        label: '文本内容',
        type: 'textarea',
        defaultValue: '示例文本',
        placeholder: '输入要显示的文本',
      ),
      param(
        key: 'fontSize',
        label: '文本大小(厘米)',
        type: 'number',
        defaultValue: 3,
        step: 0.5,
        min: 0.2,
      ),
      param(
        key: 'halign',
        label: '水平位置',
        type: 'select',
        defaultValue: 'center',
        options: [
          {'value': 'left', 'label': '靠左'},
          {'value': 'center', 'label': '居中'},
          {'value': 'right', 'label': '靠右'},
        ],
      ),
      param(
        key: 'valign',
        label: '垂直位置',
        type: 'select',
        defaultValue: 'middle',
        options: [
          {'value': 'top', 'label': '顶部'},
          {'value': 'middle', 'label': '居中'},
          {'value': 'bottom', 'label': '底部'},
        ],
      ),
      param(key: 'bgColor', label: '背景色', type: 'color', defaultValue: ''),
      param(
        key: 'textColor',
        label: '文字颜色',
        type: 'color',
        defaultValue: '#333333',
      ),
      param(
        key: 'fontFamily',
        label: '字体',
        type: 'select',
        defaultValue: 'sans-serif',
        options: kFontOptions,
      ),
    ],
    exec: kExec['text_input'],
  ),
  NodeConfig(
    id: 'colorbar_input',
    label: '色带输入',
    category: Category.input,
    description: '定义一个可调节的渐变色带:增删渐变停止点、调整颜色与位置。输出"色带",接入热力图等图表后控制其颜色映射。',
    inputs: [],
    outputs: [s('out0', '色带', SocketType.colorbar)],
    params: [
      param(
        key: 'gradient',
        label: '渐变色带',
        type: 'gradient',
        defaultValue: kDefaultGradient.map((s) => s.copy()).toList(),
        help: '点击可选中停止点,拖动调整位置;下方可改颜色,支持增删停止点',
      ),
      param(
        key: 'min',
        label: '最小值',
        type: 'number',
        defaultValue: 0,
        step: 0.1,
      ),
      param(
        key: 'max',
        label: '最大值',
        type: 'number',
        defaultValue: 1,
        step: 0.1,
      ),
      param(
        key: 'label',
        label: '色带标签',
        type: 'text',
        defaultValue: '',
        placeholder: '如:表达量',
      ),
      param(
        key: 'orientation',
        label: '方向',
        type: 'select',
        defaultValue: 'horizontal',
        options: [
          {'value': 'horizontal', 'label': '水平'},
          {'value': 'vertical', 'label': '垂直'},
        ],
      ),
    ],
    exec: kExec['colorbar_input'],
  ),
  NodeConfig(
    id: 'line_input',
    label: '线输入',
    category: Category.input,
    description: '输入一条曲线/折线:参数方程生成或手动输入点列。',
    inputs: [],
    outputs: [s('out0', '曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '线名称', type: 'text', defaultValue: '线'),
      param(
        key: 'mode',
        label: '模式',
        type: 'select',
        defaultValue: 'parametric',
        options: [
          {'value': 'parametric', 'label': '参数方程'},
          {'value': 'points', 'label': '手动点列'},
        ],
      ),
      param(key: 'fx', label: 'x = f(t)', type: 'text', defaultValue: 'x'),
      param(key: 'fy', label: 'y = f(t)', type: 'text', defaultValue: 'sin(x)'),
      param(
        key: 'start',
        label: '起始',
        type: 'number',
        defaultValue: 0,
        step: 0.1,
      ),
      param(
        key: 'end',
        label: '结束',
        type: 'number',
        defaultValue: 10,
        step: 0.1,
      ),
      param(
        key: 'count',
        label: '采样数',
        type: 'number',
        defaultValue: 200,
        step: 1,
        min: 2,
      ),
      param(
        key: 'pointsText',
        label: '点列(每行 x,y)',
        type: 'textarea',
        defaultValue: '0,0\n1,2\n2,1\n3,5',
      ),
    ],
    exec: kExec['line_input'],
  ),
  NodeConfig(
    id: 'plane_input',
    label: '平面输入',
    category: Category.input,
    description:
        '定义 x-y 平面上的一个面图元(适配 2D 坐标系或 3D 坐标系的 x-y 轴):预设圆面/椭圆面/矩形面,或自定义点列连成多边形面;可设置颜色、透明度与边缘线。',
    inputs: [],
    outputs: [s('out0', '平面', SocketType.mesh)],
    params: [
      param(key: 'name', label: '平面名称', type: 'text', defaultValue: '平面'),
      param(
        key: 'shape',
        label: '形状',
        type: 'select',
        defaultValue: 'circle',
        options: [
          {'value': 'circle', 'label': '圆面'},
          {'value': 'ellipse', 'label': '椭圆面'},
          {'value': 'rect', 'label': '矩形面'},
          {'value': 'polygon', 'label': '自定义点列(多边形面)'},
        ],
      ),
      param(
        key: 'cx',
        label: '中心 X',
        type: 'number',
        defaultValue: 0,
        step: 0.1,
      ),
      param(
        key: 'cy',
        label: '中心 Y',
        type: 'number',
        defaultValue: 0,
        step: 0.1,
      ),
      param(
        key: 'radius',
        label: '半径',
        type: 'number',
        defaultValue: 3,
        step: 0.1,
        min: 0.1,
      ),
      param(
        key: 'rx',
        label: '长半轴(X)',
        type: 'number',
        defaultValue: 3,
        step: 0.1,
        min: 0.1,
      ),
      param(
        key: 'ry',
        label: '短半轴(Y)',
        type: 'number',
        defaultValue: 2,
        step: 0.1,
        min: 0.1,
      ),
      param(
        key: 'w',
        label: '宽度',
        type: 'number',
        defaultValue: 4,
        step: 0.1,
        min: 0.1,
      ),
      param(
        key: 'h',
        label: '高度',
        type: 'number',
        defaultValue: 3,
        step: 0.1,
        min: 0.1,
      ),
      param(
        key: 'slices',
        label: '细分(圆/椭圆)',
        type: 'number',
        defaultValue: 48,
        step: 1,
        min: 3,
        max: 200,
      ),
      param(
        key: 'pointsText',
        label: '点列(每行 x,y,首尾自动闭合)',
        type: 'textarea',
        defaultValue: '0,0\n4,0\n4,3\n0,3',
        placeholder: '每行一个点坐标 x,y\n0,0\n4,0\n4,3\n0,3',
        help: '按顺序连接各点并闭合,形成多边形平面',
      ),
      param(
        key: 'color',
        label: '面颜色',
        type: 'color',
        defaultValue: '',
        help: '留空时使用渲染层默认面颜色',
      ),
      param(
        key: 'opacity',
        label: '面透明度',
        type: 'range',
        defaultValue: 0.85,
        min: 0.05,
        max: 1,
        step: 0.05,
      ),
      param(
        key: 'wireframe',
        label: '线框模式',
        type: 'boolean',
        defaultValue: false,
        help: '仅绘制三角形的边线,不填充',
      ),
      param(
        key: 'fillFaces',
        label: '填充面',
        type: 'boolean',
        defaultValue: true,
      ),
      param(
        key: 'showEdge',
        label: '显示边缘线',
        type: 'boolean',
        defaultValue: true,
      ),
      param(
        key: 'edgeColor',
        label: '边缘线颜色',
        type: 'color',
        defaultValue: '',
        help: '留空时与面颜色一致',
      ),
    ],
    exec: kExec['plane_input'],
  ),
  NodeConfig(
    id: 'grid_input',
    label: '网格数据输入',
    category: Category.input,
    description: '输入规则网格数据 z = f(x,y),用于曲面/热力图可视化。',
    inputs: [],
    outputs: [s('out0', '网格数据', SocketType.grid)],
    params: [
      param(key: 'name', label: '网格名称', type: 'text', defaultValue: '网格'),
      param(
        key: 'formula',
        label: 'z = f(x,y)',
        type: 'text',
        defaultValue: 'sin(sqrt(x*x+y*y))',
        help: '支持 x、y 变量与常用函数',
      ),
      param(
        key: 'xmin',
        label: 'X 最小',
        type: 'number',
        defaultValue: -4,
        step: 0.1,
      ),
      param(
        key: 'xmax',
        label: 'X 最大',
        type: 'number',
        defaultValue: 4,
        step: 0.1,
      ),
      param(
        key: 'ymin',
        label: 'Y 最小',
        type: 'number',
        defaultValue: -4,
        step: 0.1,
      ),
      param(
        key: 'ymax',
        label: 'Y 最大',
        type: 'number',
        defaultValue: 4,
        step: 0.1,
      ),
      param(
        key: 'nx',
        label: 'X 网格数',
        type: 'number',
        defaultValue: 40,
        step: 1,
        min: 2,
      ),
      param(
        key: 'ny',
        label: 'Y 网格数',
        type: 'number',
        defaultValue: 40,
        step: 1,
        min: 2,
      ),
    ],
    exec: kExec['grid_input'],
  ),
  NodeConfig(
    id: 'scatter_input',
    label: '聚合点输入',
    category: Category.input,
    description: '逐个添加数据点:每个点可独立设置 X/Y 坐标、大小、形状与颜色。初始只有一个加号,可不断添加。',
    inputs: [],
    outputs: [s('out0', '散点', SocketType.scatter)],
    params: [
      param(key: 'name', label: '名称', type: 'text', defaultValue: '聚合点'),
      param(
        key: 'points',
        label: '聚合点列表',
        type: 'points',
        defaultValue: <PointInput>[],
        help: '点击"＋ 添加点"逐点添加;每个点有 x/y 坐标、大小、形状、颜色',
      ),
    ],
    exec: kExec['scatter_input'],
  ),
  NodeConfig(
    id: 'series_input',
    label: '曲线输入',
    category: Category.input,
    description: '输入一条曲线:二次曲线、正弦+噪声或随机游走。',
    inputs: [],
    outputs: [s('out0', '曲线', SocketType.series)],
    params: [
      param(
        key: 'preset',
        label: '数据预设',
        type: 'select',
        defaultValue: 'quadratic',
        options: [
          {'value': 'quadratic', 'label': '二次曲线(带噪声)'},
          {'value': 'sin-noise', 'label': '正弦+噪声'},
          {'value': 'random-walk', 'label': '随机游走'},
        ],
      ),
    ],
    exec: kExec['series_input'],
  ),
  NodeConfig(
    id: 'func_curve',
    label: '函数曲线',
    category: Category.input,
    description:
        '输入函数表达式 y=f(x),输出按区间采样生成的曲线。支持 x、sin/cos/tan/exp/log/sqrt/abs、^、pi、e。',
    inputs: [],
    outputs: [s('out0', '曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '曲线名称', type: 'text', defaultValue: '函数曲线'),
      param(
        key: 'expression',
        label: 'y = f(x)',
        type: 'text',
        defaultValue: 'sin(x)',
        help: '支持 x、sin/cos/tan/exp/log/sqrt/abs、^、pi、e',
      ),
      param(
        key: 'xMin',
        label: 'X 起始',
        type: 'number',
        defaultValue: 0,
        step: 0.1,
      ),
      param(
        key: 'xMax',
        label: 'X 结束',
        type: 'number',
        defaultValue: 10,
        step: 0.1,
      ),
      param(
        key: 'samples',
        label: '采样数',
        type: 'number',
        defaultValue: 200,
        step: 1,
        min: 2,
      ),
    ],
    exec: kExec['func_curve'],
  ),

  // ================= 数据初步节点 =================
  NodeConfig(
    id: 'clean',
    label: '数据清洗',
    category: Category.clean,
    description: '清理表格:缺失值填充(零/均值/线性插值)、删除含缺失的行、去除重复行。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '清洗后表格', SocketType.table)],
    params: [
      param(
        key: 'fillMissing',
        label: '缺失值填充',
        type: 'select',
        defaultValue: 'none',
        options: [
          {'value': 'none', 'label': '不填充'},
          {'value': 'zero', 'label': '填充 0'},
          {'value': 'mean', 'label': '填充均值'},
          {'value': 'interp', 'label': '线性插值'},
        ],
      ),
      param(
        key: 'dropMissing',
        label: '删除含缺失的行',
        type: 'boolean',
        defaultValue: false,
      ),
      param(
        key: 'dedupe',
        label: '去除重复行',
        type: 'boolean',
        defaultValue: false,
      ),
    ],
    exec: kExec['clean'],
  ),
  NodeConfig(
    id: 'normalize',
    label: '标准化',
    category: Category.clean,
    description: '对数值列做 min-max 归一化或 z-score 标准化。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '标准化表格', SocketType.table)],
    params: [
      param(
        key: 'method',
        label: '方法',
        type: 'select',
        defaultValue: 'minmax',
        options: [
          {'value': 'minmax', 'label': 'min-max 归一化'},
          {'value': 'zscore', 'label': 'z-score 标准化'},
        ],
      ),
      param(
        key: 'columns',
        label: '列(留空=全部数值列)',
        type: 'text',
        defaultValue: '',
        placeholder: '如:log2FC,pvalue 或 1,2',
      ),
    ],
    exec: kExec['normalize'],
  ),
  NodeConfig(
    id: 'filter',
    label: '条件筛选',
    category: Category.clean,
    description: '按某列数值区间筛选行(可剔除离群点)。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '筛选后表格', SocketType.table)],
    params: [
      param(key: 'column', label: '筛选列', type: 'text', defaultValue: ''),
      param(key: 'min', label: '最小值(留空不限)', type: 'text', defaultValue: ''),
      param(key: 'max', label: '最大值(留空不限)', type: 'text', defaultValue: ''),
    ],
    exec: kExec['filter'],
  ),
  NodeConfig(
    id: 'sample',
    label: '数据抽样',
    category: Category.clean,
    description: '对表格抽样:取前 N 行、隔行抽样或随机抽样。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '抽样表格', SocketType.table)],
    params: [
      param(
        key: 'method',
        label: '方法',
        type: 'select',
        defaultValue: 'first',
        options: [
          {'value': 'first', 'label': '取前 N 行'},
          {'value': 'every', 'label': '隔行抽样'},
          {'value': 'random', 'label': '随机抽样'},
        ],
      ),
      param(
        key: 'count',
        label: '行数(N)',
        type: 'number',
        defaultValue: 20,
        step: 1,
        min: 0,
      ),
      param(
        key: 'step',
        label: '步长(隔行)',
        type: 'number',
        defaultValue: 2,
        step: 1,
        min: 1,
      ),
    ],
    exec: kExec['sample'],
  ),

  // ================= 数据运算节点 =================
  NodeConfig(
    id: 'derivative',
    label: '数值求导',
    category: Category.compute,
    description: '对曲线做数值求导(中心差分),输出导数曲线。',
    inputs: [s('in0', '曲线', SocketType.series)],
    outputs: [s('out0', '导数曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '导数'),
    ],
    exec: kExec['derivative'],
  ),
  NodeConfig(
    id: 'integral',
    label: '数值积分',
    category: Category.compute,
    description: '对曲线做梯形法累积积分,输出积分曲线。',
    inputs: [s('in0', '曲线', SocketType.series)],
    outputs: [s('out0', '积分曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '积分'),
    ],
    exec: kExec['integral'],
  ),
  NodeConfig(
    id: 'fit',
    label: '曲线拟合',
    category: Category.compute,
    description: '对散点做多项式(1~3 阶)或指数拟合,输出拟合曲线与系数表。',
    inputs: [s('in0', '散点', SocketType.scatter)],
    outputs: [
      s('out0', '拟合曲线', SocketType.series),
      s('out1', '系数表', SocketType.table),
    ],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '拟合曲线'),
      param(
        key: 'method',
        label: '方法',
        type: 'select',
        defaultValue: 'linear',
        options: [
          {'value': 'linear', 'label': '线性拟合'},
          {'value': 'poly', 'label': '多项式拟合'},
          {'value': 'exponential', 'label': '指数拟合'},
        ],
      ),
      param(
        key: 'degree',
        label: '多项式阶数',
        type: 'number',
        defaultValue: 2,
        step: 1,
        min: 1,
        max: 6,
      ),
    ],
    exec: kExec['fit'],
  ),
  NodeConfig(
    id: 'smooth',
    label: '平滑',
    category: Category.compute,
    description: '滑动平均平滑曲线。',
    inputs: [s('in0', '曲线', SocketType.series)],
    outputs: [s('out0', '平滑曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '平滑曲线'),
      param(
        key: 'window',
        label: '窗口半径',
        type: 'number',
        defaultValue: 5,
        step: 1,
        min: 1,
      ),
    ],
    exec: kExec['smooth'],
  ),
  NodeConfig(
    id: 'formula',
    label: '公式运算',
    category: Category.compute,
    description: '对曲线逐点计算 y\' = f(x),x 为原 x,y 为原 y。',
    inputs: [s('in0', '曲线', SocketType.series)],
    outputs: [s('out0', '结果曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '结果'),
      param(
        key: 'expression',
        label: '表达式 f(x)',
        type: 'text',
        defaultValue: '2*x + 1',
        help: '支持 x、y、sin/cos/exp/log/sqrt、^',
      ),
    ],
    exec: kExec['formula'],
  ),
  NodeConfig(
    id: 'curve_intersect',
    label: '曲线求交',
    category: Category.compute,
    description: '输入两条曲线,求折线段相交点,输出为散点(点组)。平行/共线段忽略,交点自动去重。',
    inputs: [
      s('in0', '曲线 A', SocketType.series),
      s('in1', '曲线 B', SocketType.series),
    ],
    outputs: [s('out0', '交点', SocketType.scatter)],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '交点'),
    ],
    exec: kExec['curve_intersect'],
  ),

  // ================= 数据转化节点 =================
  NodeConfig(
    id: 'extract_columns',
    label: '提取列',
    category: Category.transform,
    description: '按列名或 1 起始索引提取表格列。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '新表格', SocketType.table)],
    params: [
      param(
        key: 'columns',
        label: '列(逗号分隔)',
        type: 'text',
        defaultValue: '',
        placeholder: '如:log2FC,pvalue 或 2,4',
      ),
    ],
    exec: kExec['extract_columns'],
  ),
  NodeConfig(
    id: 'extract_rows',
    label: '提取行',
    category: Category.transform,
    description: '按行区间与步长提取表格子集。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '新表格', SocketType.table)],
    params: [
      param(
        key: 'start',
        label: '起始行(0 起始)',
        type: 'number',
        defaultValue: 0,
        step: 1,
        min: 0,
      ),
      param(
        key: 'end',
        label: '结束行',
        type: 'number',
        defaultValue: 99,
        step: 1,
        min: 0,
      ),
      param(
        key: 'step',
        label: '步长',
        type: 'number',
        defaultValue: 1,
        step: 1,
        min: 1,
      ),
    ],
    exec: kExec['extract_rows'],
  ),
  NodeConfig(
    id: 'scatter_to_table',
    label: '散点转表格',
    category: Category.transform,
    description: '把散点转换为表格(列:x、y,含三维时为 x、y、z),便于输出、清洗或继续处理。',
    inputs: [s('in0', '散点', SocketType.scatter)],
    outputs: [s('out0', '表格', SocketType.table)],
    params: [],
    exec: kExec['scatter_to_table'],
  ),
  NodeConfig(
    id: 'table_to_scatter',
    label: '表格转散点',
    category: Category.transform,
    description:
        '选取表格中两(三)列生成散点,并携带点形状/大小/颜色。点大小与点颜色可暴露为输入口,接入数据列后每个点的大小/颜色与该行数值成正比。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '散点', SocketType.scatter)],
    params: [
      param(key: 'name', label: '名称', type: 'text', defaultValue: '散点'),
      param(key: 'xCol', label: 'X 列', type: 'text', defaultValue: ''),
      param(key: 'yCol', label: 'Y 列', type: 'text', defaultValue: ''),
      param(key: 'zCol', label: 'Z 列(可选,三维)', type: 'text', defaultValue: ''),
      param(
        key: 'pointShape',
        label: '点形状',
        type: 'select',
        defaultValue: 'circle',
        options: kShapeOptions,
      ),
      param(
        key: 'pointSize',
        label: '点大小',
        type: 'range',
        defaultValue: 4,
        min: 1,
        max: 16,
        step: 0.5,
        expose: true,
      ),
      param(
        key: 'pointColor',
        label: '点颜色',
        type: 'color',
        defaultValue: '#1f77b4',
        expose: true,
      ),
    ],
    exec: kExec['table_to_scatter'],
  ),
  NodeConfig(
    id: 'table_to_series',
    label: '表格转曲线',
    category: Category.transform,
    description: '选取表格中两列生成曲线,并携带线形状/粗细/颜色。线宽与线颜色可暴露为输入口,接入数据列后逐段变化。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '名称', type: 'text', defaultValue: '曲线'),
      param(key: 'xCol', label: 'X 列', type: 'text', defaultValue: ''),
      param(key: 'yCol', label: 'Y 列', type: 'text', defaultValue: ''),
      param(
        key: 'lineStyle',
        label: '线形状',
        type: 'select',
        defaultValue: 'solid',
        options: [
          {'value': 'solid', 'label': '实线'},
          {'value': 'dashed', 'label': '虚线'},
        ],
      ),
      param(
        key: 'lineWidth',
        label: '线宽',
        type: 'range',
        defaultValue: 2,
        min: 0.5,
        max: 10,
        step: 0.5,
        expose: true,
      ),
      param(
        key: 'lineColor',
        label: '线颜色',
        type: 'color',
        defaultValue: '#ff7f0e',
        expose: true,
      ),
    ],
    exec: kExec['table_to_series'],
  ),
  NodeConfig(
    id: 'series_to_scatter',
    label: '曲线转散点',
    category: Category.transform,
    description: '将曲线数据转化为散点数据,并携带点形状/大小/颜色。点大小与点颜色可暴露为输入口,接入数据列后逐点变化。',
    inputs: [s('in0', '曲线', SocketType.series)],
    outputs: [s('out0', '散点', SocketType.scatter)],
    params: [
      param(key: 'name', label: '名称', type: 'text', defaultValue: '散点'),
      param(
        key: 'pointShape',
        label: '点形状',
        type: 'select',
        defaultValue: 'circle',
        options: kShapeOptions,
      ),
      param(
        key: 'pointSize',
        label: '点大小',
        type: 'range',
        defaultValue: 4,
        min: 1,
        max: 16,
        step: 0.5,
        expose: true,
      ),
      param(
        key: 'pointColor',
        label: '点颜色',
        type: 'color',
        defaultValue: '#1f77b4',
        expose: true,
      ),
    ],
    exec: kExec['series_to_scatter'],
  ),

  // ================= 数据可视化节点 =================
  NodeConfig(
    id: 'viz_scatter',
    label: '散点图',
    category: Category.visualize,
    description: '以表格两列绘制散点图;也可直接接入散点/曲线数据可视化。',
    inputs: [
      s('in0', '表格', SocketType.table),
      s('in1', '散点(可选)', SocketType.scatter),
      s('in2', '曲线(可选)', SocketType.series),
      ...kOverlaySockets,
    ],
    outputs: [],
    params: [
      param(
        key: 'xCol',
        label: 'X 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(
        key: 'yCol',
        label: 'Y 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_line',
    label: '折线图',
    category: Category.visualize,
    description: '以表格一列(或多条曲线)绘制折线图。',
    inputs: [
      s('in0', '表格', SocketType.table),
      s('in1', '曲线(可选)', SocketType.series),
      ...kOverlaySockets,
    ],
    outputs: [],
    params: [
      param(
        key: 'xCol',
        label: 'X 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(
        key: 'yCol',
        label: 'Y 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_bar',
    label: '柱状图',
    category: Category.visualize,
    description: '以表格两列绘制柱状图(分类 + 数值)。',
    inputs: [s('in0', '表格', SocketType.table), ...kOverlaySockets],
    outputs: [],
    params: [
      param(
        key: 'xCol',
        label: 'X 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(
        key: 'yCol',
        label: 'Y 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_volcano',
    label: '火山图',
    category: Category.visualize,
    description: '差异分析火山图:以 log2FC 与 p 值两列绘制,自动标注显著点。',
    inputs: [s('in0', '表格', SocketType.table), ...kOverlaySockets],
    outputs: [],
    params: [
      param(
        key: 'fcCol',
        label: 'log2FC 列',
        type: 'text',
        defaultValue: 'log2FC',
      ),
      param(key: 'pCol', label: 'p 值列', type: 'text', defaultValue: 'pvalue'),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_heatmap',
    label: '热力图',
    category: Category.visualize,
    description:
        '数值矩阵热力图:取表格前 10 个数值列,行数自动降采样以保证流畅。可接入"色带输入"自定义颜色渐变,或在属性面板直接编辑渐变。',
    inputs: [
      s('in0', '表格', SocketType.table),
      s('in1', '色带(颜色渐变)', SocketType.colorbar),
      ...kOverlaySockets,
    ],
    outputs: [],
    params: [
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
      param(
        key: 'gradient',
        label: '颜色渐变',
        type: 'gradient',
        defaultValue: kDefaultGradient.map((s) => s.copy()).toList(),
        help: '热力图颜色映射渐变;接入色带输入时优先使用输入色带',
      ),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_box',
    label: '箱线图',
    category: Category.visualize,
    description: '多组数值分布箱线图:每个数值列一个箱体。',
    inputs: [s('in0', '表格', SocketType.table), ...kOverlaySockets],
    outputs: [],
    params: [
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_violin',
    label: '小提琴图',
    category: Category.visualize,
    description: '多组数值分布小提琴图(核密度估计):每个数值列一个小提琴。',
    inputs: [s('in0', '表格', SocketType.table), ...kOverlaySockets],
    outputs: [],
    params: [
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_sankey',
    label: '桑基图',
    category: Category.visualize,
    description: '流程/流量桑基图:按源列→目标列聚合权重。',
    inputs: [s('in0', '表格', SocketType.table), ...kOverlaySockets],
    outputs: [],
    params: [
      param(
        key: 'sourceCol',
        label: '源列',
        type: 'text',
        defaultValue: '',
        help: '起点列',
      ),
      param(
        key: 'targetCol',
        label: '目标列',
        type: 'text',
        defaultValue: '',
        help: '终点列',
      ),
      param(
        key: 'valueCol',
        label: '权重列(可选)',
        type: 'text',
        defaultValue: '',
        help: '留空按出现次数',
      ),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_graph',
    label: '网络示意图',
    category: Category.visualize,
    description: '关系网络图(力导向布局):按源列→目标列构建边。',
    inputs: [s('in0', '表格', SocketType.table), ...kOverlaySockets],
    outputs: [],
    params: [
      param(
        key: 'sourceCol',
        label: '源列',
        type: 'text',
        defaultValue: '',
        help: '起点列',
      ),
      param(
        key: 'targetCol',
        label: '目标列',
        type: 'text',
        defaultValue: '',
        help: '终点列',
      ),
      param(
        key: 'valueCol',
        label: '权重列(可选)',
        type: 'text',
        defaultValue: '',
        help: '留空按出现次数',
      ),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_principled',
    label: '原理化输出',
    category: Category.visualize,
    description:
        '原理化模式:接收点/线/面(均可多路连接)、分布、文本与坐标系,所有图元缩放至互相垂直的坐标轴盒内部,预览窗与坐标系尺寸等比例。',
    inputs: [
      s('in0', '点(散点·可多连)', SocketType.scatter, multi: true),
      s('in1', '线(曲线·可多连)', SocketType.series, multi: true),
      s('in2', '面(网格·可多连)', SocketType.mesh, multi: true),
      s('in3', '分布', SocketType.distribution),
      s('in4', '坐标系', SocketType.axes),
      s('in5', '文本(可多连)', SocketType.text, multi: true),
    ],
    outputs: [],
    params: [
      param(
        key: 'colorPreset',
        label: '颜色预设',
        type: 'select',
        defaultValue: 'paper',
        options: [
          {'value': 'paper', 'label': '论文白(亮色)'},
          {'value': 'custom', 'label': '自定义(使用下方颜色)'},
          {'value': 'tech', 'label': '暗色科技'},
          {'value': 'ocean', 'label': '海洋蓝'},
          {'value': 'sunset', 'label': '落日橙'},
          {'value': 'forest', 'label': '森林绿'},
          {'value': 'neon', 'label': '霓虹紫'},
          {'value': 'gray', 'label': '灰度'},
        ],
      ),
      param(
        key: 'axisColor',
        label: '坐标轴颜色(统一单色)',
        type: 'color',
        defaultValue: '#333333',
      ),
      param(
        key: 'bgColor',
        label: '背景色',
        type: 'color',
        defaultValue: '#ffffff',
      ),
      param(
        key: 'canvasPxW',
        label: '导出宽度(像素)',
        type: 'number',
        defaultValue: 1920,
        step: 10,
        min: 100,
        max: 8000,
        help: '仅影响导出 PNG(含预览 PNG)的像素数量,不影响预览显示效果与图表视觉(线条粗细/文字大小等)',
      ),
      param(
        key: 'canvasPxH',
        label: '导出高度(像素)',
        type: 'number',
        defaultValue: 1200,
        step: 10,
        min: 100,
        max: 8000,
        help: '仅影响导出 PNG(含预览 PNG)的像素数量,不影响预览显示效果与图表视觉(线条粗细/文字大小等)',
      ),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'data_output',
    label: '数据输出',
    category: Category.visualize,
    description: '输出节点:显示传入表格数据的预览(列名 + 前若干行),便于检查流水线中间结果。',
    inputs: [s('in0', '表格', SocketType.table), ...kOverlaySockets],
    outputs: [],
    params: [
      param(
        key: 'maxRows',
        label: '预览行数',
        type: 'number',
        defaultValue: 8,
        step: 1,
        min: 1,
        max: 50,
      ),
    ],
    isViewer: true,
  ),
];

final Map<String, NodeConfig> _configMap = {
  for (final c in kNodeConfigs) c.id: c,
};

NodeConfig? getConfig(String id) => _configMap[id];

List<NodeConfig> nodesByCategory(Category cat) =>
    kNodeConfigs.where((c) => c.category == cat).toList();
