// 节点注册表(由 React 版 nodes/registry.ts 移植)
library;

import 'data.dart';
import 'exec.dart';

Socket s(String id, String name, SocketType type, {bool? multi}) =>
    Socket(id: id, name: name, type: type, multi: multi);

ParamSpec param({
  required String key,
  required String label,
  required String type,
  dynamic defaultValue,
  List<Map<String, String>>? options,
  double? min,
  double? max,
  double? step,
  String? placeholder,
  String? help,
  bool? expose,
  String? action,
  String? dependsOn,
  List<String>? visibleWhenValues,
}) => ParamSpec(
  key: key,
  label: label,
  type: type,
  defaultValue: defaultValue,
  options: options,
  min: min,
  max: max,
  step: step,
  placeholder: placeholder,
  help: help,
  expose: expose,
  action: action,
  dependsOn: dependsOn,
  visibleWhenValues: visibleWhenValues,
);

const List<Map<String, String>> kFontOptions = [
  {'value': 'sans-serif', 'label': '默认 (sans-serif)'},
  {'value': 'Microsoft YaHei', 'label': '微软雅黑'},
  {'value': 'SimSun', 'label': '宋体'},
  {'value': 'SimHei', 'label': '黑体'},
  {'value': 'KaiTi', 'label': '楷体'},
  {'value': 'monospace', 'label': '等宽 (monospace)'},
  {'value': 'Courier New', 'label': 'Courier New'},
];

const List<Map<String, String>> kShapeOptions = [
  {'value': 'circle', 'label': '圆形'},
  {'value': 'square', 'label': '方形'},
  {'value': 'diamond', 'label': '菱形'},
  {'value': 'triangle', 'label': '三角形'},
];

/// 曲线样式参数(供所有输出曲线/线的节点复用;键名与 table_to_series 一致)。
/// 三个参数均可暴露为输入口,接入数据列后线宽/颜色逐段变化。
List<ParamSpec> lineStyleParams() => [
  param(
    key: 'lineStyle',
    label: '线显示形式',
    type: 'select',
    defaultValue: 'solid',
    options: [
      {'value': 'solid', 'label': '实线'},
      {'value': 'dashed', 'label': '虚线'},
    ],
    expose: true,
  ),
  param(
    key: 'lineWidth',
    label: '线宽',
    type: 'range',
    defaultValue: 2,
    min: 0.5,
    max: 10,
    step: 0.5,
    expose: true,
  ),
  param(
    key: 'lineColor',
    label: '线颜色',
    type: 'color',
    defaultValue: '#ff7f0e',
    expose: true,
  ),
];

/// 点样式参数(供所有输出散点/点的节点复用;键名与 series_to_scatter 一致)。
/// 三个参数均可暴露为输入口,接入数据列后点大小/颜色逐点变化。
List<ParamSpec> pointStyleParams() => [
  param(
    key: 'pointShape',
    label: '点形状',
    type: 'select',
    defaultValue: 'circle',
    options: kShapeOptions,
    expose: true,
  ),
  param(
    key: 'pointSize',
    label: '点大小',
    type: 'range',
    defaultValue: 4,
    min: 1,
    max: 16,
    step: 0.5,
    expose: true,
  ),
  param(
    key: 'pointColor',
    label: '点颜色',
    type: 'color',
    defaultValue: '#1f77b4',
    expose: true,
  ),
];

/// 图表图元叠加输入口(点/线/面/文本,均可多连):各可视化节点共用。
/// 接入的图元像"原理化输出"一样直接绘制进图中(见 viewer.dart 图元叠加渲染)。
final List<Socket> kOverlaySockets = [
  Socket(
    id: 'in_pts',
    name: '点(散点·可多连)',
    type: SocketType.scatter,
    multi: true,
  ),
  Socket(
    id: 'in_lines',
    name: '线(曲线·可多连)',
    type: SocketType.series,
    multi: true,
  ),
  Socket(id: 'in_faces', name: '面(网格·可多连)', type: SocketType.mesh, multi: true),
  Socket(id: 'in_texts', name: '文本(可多连)', type: SocketType.text, multi: true),
];

final List<NodeConfig> kNodeConfigs = [
  // ================= 组输入节点 =================
  NodeConfig(
    id: 'table_input',
    label: '表格输入',
    category: Category.input,
    description:
        '输入表格数据:支持内置预设(火山图/销售/鸢尾花/物理曲线),或从 CSV/Excel 文件导入;导入后节点标题显示文件名。',
    inputs: [],
    outputs: [s('out0', '表格', SocketType.table)],
    titleParam: 'name',
    params: [
      param(
        key: 'preset',
        label: '数据预设',
        type: 'select',
        defaultValue: 'volcano',
        options: [
          {'value': 'volcano', 'label': '火山图数据(基因表达)'},
          {'value': 'sales', 'label': '销售数据'},
          {'value': 'iris', 'label': '鸢尾花数据'},
          {'value': 'phys', 'label': '物理曲线(带噪声)'},
        ],
      ),
      param(
        key: 'mode',
        label: '数据来源',
        type: 'select',
        defaultValue: 'preset',
        options: [
          {'value': 'preset', 'label': '使用预设'},
          {'value': 'manual', 'label': '文件数据'},
        ],
      ),
      param(
        key: 'headerMode',
        label: '表头',
        type: 'select',
        defaultValue: 'auto',
        options: [
          {'value': 'auto', 'label': '自动检测'},
          {'value': 'present', 'label': '第一行为表头'},
          {'value': 'absent', 'label': '无表头'},
        ],
      ),
      param(
        key: 'encodingMode',
        label: 'UTF-8 解码',
        type: 'select',
        defaultValue: 'strict',
        options: const [
          {'value': 'strict', 'label': '严格（推荐）'},
          {'value': 'replace', 'label': '替换损坏字节'},
        ],
      ),
      param(
        key: 'seed',
        label: '随机种子',
        type: 'number',
        defaultValue: 0,
        step: 1,
      ),
      param(key: 'name', label: '名称', type: 'text', defaultValue: ''),
      param(
        key: 'import',
        label: '从 CSV/Excel 文件导入',
        type: 'button',
        defaultValue: null,
        action: 'import-csv',
      ),
    ],
    exec: kExec['table_input'],
  ),
  NodeConfig(
    id: 'axis_input',
    label: '坐标系输入',
    category: Category.input,
    description:
        '定义一个坐标系及其场景内容:维度(2D/3D)、各轴厘米长度、X/Y 起止数字、坐标轴定位方式(以原点为中心/总贴左边沿)、预设类型、各轴独立颜色/粗细(厘米)/网格开关、文字样式、3D 视角旋转与导出像素大小。点/线/面/分布/文本接入后直接实例化到坐标系内,由"原理化输出"仅负责渲染。',
    inputs: [
      s('in0', '点(散点·可多连)', SocketType.scatter, multi: true),
      s('in1', '线(曲线·可多连)', SocketType.series, multi: true),
      s('in2', '面(网格·可多连)', SocketType.mesh, multi: true),
      s('in3', '分布', SocketType.distribution),
      s('in4', '文本(可多连)', SocketType.text, multi: true),
    ],
    outputs: [s('out0', '坐标系', SocketType.axes)],
    params: [
      param(key: 'name', label: '坐标系名称', type: 'text', defaultValue: '坐标系'),
      param(
        key: 'dim',
        label: '维度',
        type: 'select',
        defaultValue: '3d',
        options: [
          {'value': '3d', 'label': '三维 (X, Y, Z)'},
          {'value': '2d', 'label': '二维 (X, Y)'},
        ],
      ),
      param(
        key: 'axisVisibility',
        label: '坐标轴显示',
        type: 'select',
        defaultValue: 'visible',
        options: [
          {'value': 'visible', 'label': '显示'},
          {'value': 'hidden', 'label': '隐藏'},
        ],
      ),
      param(
        key: 'xLen',
        label: 'X 轴长度(厘米)',
        type: 'number',
        defaultValue: 16,
        step: 0.5,
        min: 1,
      ),
      param(
        key: 'yLen',
        label: 'Y 轴长度(厘米)',
        type: 'number',
        defaultValue: 10,
        step: 0.5,
        min: 1,
      ),
      param(
        key: 'zLen',
        label: 'Z 轴长度(厘米,3D)',
        type: 'number',
        defaultValue: 8,
        step: 0.5,
        min: 1,
        dependsOn: 'dim',
        visibleWhenValues: ['3d'],
      ),
      param(
        key: 'aspectMode',
        label: '数据纵横比',
        type: 'select',
        defaultValue: 'equal',
        options: [
          {'value': 'equal', 'label': '等比例 (equal/data)'},
          {'value': 'free', 'label': '自由填充坐标盒'},
        ],
        help: '等比例模式让三个轴上的一个数据单位具有相同屏幕尺度，球面不会被拉成椭球。',
      ),
      for (final axis in ['X', 'Y', 'Z'])
        param(
          key: '${axis.toLowerCase()}Scale',
          label: '$axis 轴尺度',
          type: 'select',
          defaultValue: 'linear',
          options: [
            {'value': 'linear', 'label': '线性'},
            {'value': 'log10', 'label': 'Log10'},
            {'value': 'log2', 'label': 'Log2'},
            {'value': 'symlog', 'label': '对称对数 Symlog'},
            {'value': 'time', 'label': '时间（Unix 毫秒）'},
          ],
          help: '对数尺度要求坐标范围为正；数据中的非正值会作为缺失点断开。',
          dependsOn: axis == 'Z' ? 'dim' : null,
          visibleWhenValues: axis == 'Z' ? ['3d'] : null,
        ),
      param(
        key: 'symlogThreshold',
        label: 'Symlog 线性阈值',
        type: 'number',
        defaultValue: 1,
        min: 1e-12,
        step: 0.1,
      ),
      param(
        key: 'xStart',
        label: 'X 起始数字',
        type: 'number',
        defaultValue: -5,
        step: 0.1,
      ),
      param(
        key: 'xEnd',
        label: 'X 结束数字',
        type: 'number',
        defaultValue: 5,
        step: 0.1,
      ),
      param(
        key: 'yStart',
        label: 'Y 起始数字',
        type: 'number',
        defaultValue: -5,
        step: 0.1,
      ),
      param(
        key: 'yEnd',
        label: 'Y 结束数字',
        type: 'number',
        defaultValue: 5,
        step: 0.1,
      ),
      param(
        key: 'zStart',
        label: 'Z 起始数字(3D)',
        type: 'number',
        defaultValue: -5,
        step: 0.1,
        dependsOn: 'dim',
        visibleWhenValues: ['3d'],
      ),
      param(
        key: 'zEnd',
        label: 'Z 结束数字(3D)',
        type: 'number',
        defaultValue: 5,
        step: 0.1,
        dependsOn: 'dim',
        visibleWhenValues: ['3d'],
      ),
      param(
        key: 'axisOrigin',
        label: '坐标轴位置',
        type: 'select',
        defaultValue: 'origin',
        options: [
          {'value': 'origin', 'label': '以原点为中心(有原点过原点,否则贴边)'},
          {'value': 'left', 'label': '总贴左边沿'},
        ],
      ),
      param(
        key: 'showBorder',
        label: '显示边界边框',
        type: 'boolean',
        defaultValue: true,
      ),
      param(
        key: 'axisColorX',
        label: 'X 轴颜色',
        type: 'color',
        defaultValue: '#333333',
      ),
      param(
        key: 'axisColorY',
        label: 'Y 轴颜色',
        type: 'color',
        defaultValue: '#333333',
      ),
      param(
        key: 'axisColorZ',
        label: 'Z 轴颜色(3D)',
        type: 'color',
        defaultValue: '#333333',
        dependsOn: 'dim',
        visibleWhenValues: ['3d'],
      ),
      param(
        key: 'axisWidthX',
        label: 'X 轴粗细(厘米)',
        type: 'number',
        defaultValue: 0.12,
        step: 0.02,
        min: 0.02,
        max: 1,
      ),
      param(
        key: 'axisWidthY',
        label: 'Y 轴粗细(厘米)',
        type: 'number',
        defaultValue: 0.12,
        step: 0.02,
        min: 0.02,
        max: 1,
      ),
      param(
        key: 'axisWidthZ',
        label: 'Z 轴粗细(厘米,3D)',
        type: 'number',
        defaultValue: 0.12,
        step: 0.02,
        min: 0.02,
        max: 1,
        dependsOn: 'dim',
        visibleWhenValues: ['3d'],
      ),
      param(
        key: 'gridX',
        label: 'X 方向网格线',
        type: 'boolean',
        defaultValue: true,
      ),
      param(
        key: 'gridY',
        label: 'Y 方向网格线',
        type: 'boolean',
        defaultValue: true,
      ),
      param(
        key: 'gridZ',
        label: 'Z 方向网格线(3D)',
        type: 'boolean',
        defaultValue: true,
        dependsOn: 'dim',
        visibleWhenValues: ['3d'],
      ),
      param(
        key: 'fontSize',
        label: '文字大小(px)',
        type: 'number',
        defaultValue: 10,
        step: 1,
        min: 6,
        max: 24,
      ),
      param(
        key: 'fontFamily',
        label: '字体',
        type: 'select',
        defaultValue: 'sans-serif',
        options: kFontOptions,
      ),
      param(key: 'labelX', label: 'X 轴标签', type: 'text', defaultValue: 'X'),
      param(key: 'labelY', label: 'Y 轴标签', type: 'text', defaultValue: 'Y'),
      param(
        key: 'labelZ',
        label: 'Z 轴标签(3D)',
        type: 'text',
        defaultValue: 'Z',
        dependsOn: 'dim',
        visibleWhenValues: ['3d'],
      ),
      param(
        key: 'arrowX',
        label: 'X 轴箭头',
        type: 'boolean',
        defaultValue: true,
        help: '在 X 轴末端绘制箭头',
      ),
      param(
        key: 'arrowY',
        label: 'Y 轴箭头',
        type: 'boolean',
        defaultValue: true,
        help: '在 Y 轴末端绘制箭头',
      ),
      param(
        key: 'rotX',
        label: '旋转 X(度)',
        type: 'range',
        defaultValue: -20,
        min: -180,
        max: 180,
        step: 1,
        help: '原理化输出中的 3D 视角旋转(绕 X 轴,度)',
        dependsOn: 'dim',
        visibleWhenValues: ['3d'],
      ),
      param(
        key: 'rotY',
        label: '旋转 Y(度)',
        type: 'range',
        defaultValue: 25,
        min: -180,
        max: 180,
        step: 1,
        help: '原理化输出中的 3D 视角旋转(绕 Y 轴,度)',
        dependsOn: 'dim',
        visibleWhenValues: ['3d'],
      ),
      param(
        key: 'rotZ',
        label: '旋转 Z(度)',
        type: 'range',
        defaultValue: 0,
        min: -180,
        max: 180,
        step: 1,
        help: '原理化输出中的 3D 视角旋转(绕 Z 轴,度)',
        dependsOn: 'dim',
        visibleWhenValues: ['3d'],
      ),
      param(
        key: 'colorPreset',
        label: '场景颜色预设',
        type: 'select',
        defaultValue: 'paper',
        options: [
          {'value': 'paper', 'label': '论文白(亮色)'},
          {'value': 'custom', 'label': '自定义(使用下方背景色)'},
          {'value': 'tech', 'label': '暗色科技'},
          {'value': 'ocean', 'label': '海洋蓝'},
          {'value': 'sunset', 'label': '落日橙'},
          {'value': 'forest', 'label': '森林绿'},
          {'value': 'neon', 'label': '霓虹紫'},
          {'value': 'gray', 'label': '灰度'},
        ],
        help: '控制原理化渲染时的背景与图元默认配色',
      ),
      param(
        key: 'bgColor',
        label: '背景色',
        type: 'color',
        defaultValue: '#ffffff',
        dependsOn: 'colorPreset',
        visibleWhenValues: ['custom'],
      ),
      param(
        key: 'exportPreset',
        label: '论文尺寸预设',
        type: 'select',
        defaultValue: 'custom',
        options: [
          {'value': 'custom', 'label': '自定义'},
          {'value': 'single', 'label': '期刊单栏 89 mm'},
          {'value': 'double', 'label': '期刊双栏 183 mm'},
          {'value': 'poster', 'label': '海报 420×297 mm'},
          {'value': 'slides', 'label': '演示文稿 13.333×7.5 in'},
        ],
      ),
      param(
        key: 'exportUnit',
        label: '导出尺寸单位',
        type: 'select',
        defaultValue: 'px',
        options: [
          {'value': 'px', 'label': '像素 px'},
          {'value': 'mm', 'label': '毫米 mm'},
          {'value': 'inch', 'label': '英寸 inch'},
        ],
        dependsOn: 'exportPreset',
        visibleWhenValues: ['custom'],
      ),
      param(
        key: 'exportWidth',
        label: '导出宽度',
        type: 'number',
        defaultValue: 1920,
        min: 1,
        step: 1,
        dependsOn: 'exportPreset',
        visibleWhenValues: ['custom'],
      ),
      param(
        key: 'exportHeight',
        label: '导出高度',
        type: 'number',
        defaultValue: 1200,
        min: 1,
        step: 1,
        dependsOn: 'exportPreset',
        visibleWhenValues: ['custom'],
      ),
      param(
        key: 'exportDpi',
        label: '导出 DPI',
        type: 'number',
        defaultValue: 300,
        min: 36,
        max: 2400,
        step: 1,
      ),
      param(
        key: 'fontExportStrategy',
        label: '矢量字体策略',
        type: 'select',
        defaultValue: 'embed',
        options: [
          {'value': 'embed', 'label': '嵌入（可用时）'},
          {'value': 'outline', 'label': '轮廓化（不可用时回退嵌入）'},
          {'value': 'system', 'label': '保留可编辑文本'},
        ],
      ),
      param(
        key: 'legendMode',
        label: '图例',
        type: 'select',
        defaultValue: 'auto',
        options: [
          {'value': 'auto', 'label': '自动'},
          {'value': 'manual', 'label': '手动排序'},
          {'value': 'hidden', 'label': '隐藏'},
        ],
      ),
      param(
        key: 'legendPosition',
        label: '图例位置',
        type: 'select',
        defaultValue: 'right',
        options: [
          {'value': 'right', 'label': '右上'},
          {'value': 'left', 'label': '左上'},
          {'value': 'bottom', 'label': '底部'},
        ],
        dependsOn: 'legendMode',
        visibleWhenValues: ['auto', 'manual'],
      ),
      param(
        key: 'legendGrouping',
        label: '图例分组',
        type: 'select',
        defaultValue: 'type',
        options: [
          {'value': 'type', 'label': '按图元类型'},
          {'value': 'none', 'label': '不分组'},
        ],
        dependsOn: 'legendMode',
        visibleWhenValues: ['auto', 'manual'],
      ),
      param(
        key: 'legendOrder',
        label: '图例手动顺序',
        type: 'text',
        defaultValue: '',
        help: '用英文逗号分隔系列名称；未列出的项目排在末尾',
        dependsOn: 'legendMode',
        visibleWhenValues: ['manual'],
      ),
      param(
        key: 'legendHidden',
        label: '隐藏图例项',
        type: 'text',
        defaultValue: '',
        help: '用英文逗号分隔需要隐藏的系列名称',
        dependsOn: 'legendMode',
        visibleWhenValues: ['auto', 'manual'],
      ),
    ],
    exec: kExec['axis_input'],
  ),
  NodeConfig(
    id: 'text_input',
    label: '文本输入',
    category: Category.input,
    description:
        '定义一个文本图元:内容、文本大小(厘米)、在坐标轴盒内的位置、背景色/文字颜色与字体。接入"原理化输出"后按厘米比例绘制。',
    inputs: [],
    outputs: [s('out0', '文本', SocketType.text)],
    params: [
      param(
        key: 'text',
        label: '文本内容',
        type: 'textarea',
        defaultValue: '示例文本',
        placeholder: '输入要显示的文本',
      ),
      param(
        key: 'fontSize',
        label: '文本大小(厘米)',
        type: 'number',
        defaultValue: 3,
        step: 0.5,
        min: 0.2,
      ),
      param(
        key: 'halign',
        label: '水平位置',
        type: 'select',
        defaultValue: 'center',
        options: [
          {'value': 'left', 'label': '靠左'},
          {'value': 'center', 'label': '居中'},
          {'value': 'right', 'label': '靠右'},
        ],
      ),
      param(
        key: 'valign',
        label: '垂直位置',
        type: 'select',
        defaultValue: 'middle',
        options: [
          {'value': 'top', 'label': '顶部'},
          {'value': 'middle', 'label': '居中'},
          {'value': 'bottom', 'label': '底部'},
        ],
      ),
      param(key: 'bgColor', label: '背景色', type: 'color', defaultValue: ''),
      param(
        key: 'textColor',
        label: '文字颜色',
        type: 'color',
        defaultValue: '#333333',
      ),
      param(
        key: 'fontFamily',
        label: '字体',
        type: 'select',
        defaultValue: 'sans-serif',
        options: kFontOptions,
      ),
    ],
    exec: kExec['text_input'],
  ),
  NodeConfig(
    id: 'colorbar_input',
    label: '色带输入',
    category: Category.input,
    description: '定义一个可调节的渐变色带:增删渐变停止点、调整颜色与位置。输出"色带",接入热力图等图表后控制其颜色映射。',
    inputs: [],
    outputs: [s('out0', '色带', SocketType.colorbar)],
    params: [
      param(
        key: 'gradient',
        label: '渐变色带',
        type: 'gradient',
        defaultValue: kDefaultGradient.map((s) => s.copy()).toList(),
        help: '点击可选中停止点,拖动调整位置;下方可改颜色,支持增删停止点',
      ),
      param(
        key: 'min',
        label: '最小值',
        type: 'number',
        defaultValue: 0,
        step: 0.1,
      ),
      param(
        key: 'max',
        label: '最大值',
        type: 'number',
        defaultValue: 1,
        step: 0.1,
      ),
      param(
        key: 'label',
        label: '色带标签',
        type: 'text',
        defaultValue: '',
        placeholder: '如:表达量',
      ),
      param(
        key: 'orientation',
        label: '方向',
        type: 'select',
        defaultValue: 'horizontal',
        options: [
          {'value': 'horizontal', 'label': '水平'},
          {'value': 'vertical', 'label': '垂直'},
        ],
      ),
    ],
    exec: kExec['colorbar_input'],
  ),
  NodeConfig(
    id: 'surface_input',
    label: '曲面输入',
    category: Category.input,
    description: '生成显式、参数或隐式曲面，也可重建规则表格网格。隐式模式接受 F(x,y,z)=0 或 lhs=rhs。',
    inputs: [
      s('in0', '网格表格', SocketType.table),
      s('in1', '色带', SocketType.colorbar),
    ],
    outputs: [s('out0', '曲面', SocketType.mesh)],
    params: [
      param(key: 'name', label: '曲面名称', type: 'text', defaultValue: '曲面'),
      param(
        key: 'mode',
        label: '生成方式',
        type: 'select',
        defaultValue: 'explicit',
        options: [
          {'value': 'explicit', 'label': '显式 z=f(x,y)'},
          {'value': 'parametric', 'label': '参数曲面'},
          {'value': 'implicit', 'label': '隐式 F(x,y,z)=0'},
          {'value': 'grid', 'label': '表格网格'},
          {'value': 'preset', 'label': '预设曲面'},
        ],
      ),
      param(
        key: 'preset',
        label: '预设',
        type: 'select',
        defaultValue: 'plane',
        dependsOn: 'mode',
        visibleWhenValues: ['preset'],
        options: [
          {'value': 'plane', 'label': '平面'},
          {'value': 'disk', 'label': '圆盘'},
          {'value': 'ellipse', 'label': '椭圆盘'},
          {'value': 'sphere', 'label': '球面'},
          {'value': 'cylinder', 'label': '圆柱面'},
          {'value': 'cone', 'label': '圆锥面'},
          {'value': 'torus', 'label': '环面'},
          {'value': 'paraboloid', 'label': '抛物面'},
          {'value': 'saddle', 'label': '马鞍面'},
          {'value': 'gaussian', 'label': '高斯曲面'},
        ],
      ),
      param(
        key: 'exprZ',
        label: 'z(x,y) / z(u,v)',
        type: 'text',
        defaultValue: 'sin(x)*cos(y)',
        dependsOn: 'mode',
        visibleWhenValues: ['explicit', 'parametric'],
      ),
      param(
        key: 'exprX',
        label: 'x(u,v)',
        type: 'text',
        defaultValue: 'x',
        dependsOn: 'mode',
        visibleWhenValues: ['parametric'],
      ),
      param(
        key: 'implicitExpr',
        label: '隐式方程',
        type: 'text',
        defaultValue: 'x^2+y^2+z^2=1',
        dependsOn: 'mode',
        visibleWhenValues: ['implicit'],
        help: '可输入 F(x,y,z)=0，也可直接输入等式，如 x^2+y^2+z^2=1。',
      ),
      param(
        key: 'exprY',
        label: 'y(u,v)',
        type: 'text',
        defaultValue: 'y',
        dependsOn: 'mode',
        visibleWhenValues: ['parametric'],
      ),
      param(
        key: 'xMin',
        label: 'X/U 最小值',
        type: 'number',
        defaultValue: -3,
        step: 0.1,
      ),
      param(
        key: 'xMax',
        label: 'X/U 最大值',
        type: 'number',
        defaultValue: 3,
        step: 0.1,
      ),
      param(
        key: 'yMin',
        label: 'Y/V 最小值',
        type: 'number',
        defaultValue: -3,
        step: 0.1,
      ),
      param(
        key: 'yMax',
        label: 'Y/V 最大值',
        type: 'number',
        defaultValue: 3,
        step: 0.1,
      ),
      param(
        key: 'zMin',
        label: 'Z 最小值',
        type: 'number',
        defaultValue: -3,
        step: 0.1,
        dependsOn: 'mode',
        visibleWhenValues: ['implicit'],
      ),
      param(
        key: 'zMax',
        label: 'Z 最大值',
        type: 'number',
        defaultValue: 3,
        step: 0.1,
        dependsOn: 'mode',
        visibleWhenValues: ['implicit'],
      ),
      param(
        key: 'rows',
        label: 'U/X 采样数',
        type: 'number',
        defaultValue: 31,
        min: 2,
        max: 400,
        step: 1,
      ),
      param(
        key: 'columns',
        label: 'V/Y 采样数',
        type: 'number',
        defaultValue: 31,
        min: 2,
        max: 400,
        step: 1,
      ),
      param(
        key: 'depthSamples',
        label: 'Z 采样数',
        type: 'number',
        defaultValue: 25,
        min: 2,
        max: 100,
        step: 1,
        dependsOn: 'mode',
        visibleWhenValues: ['implicit'],
      ),
      param(
        key: 'wrapRows',
        label: 'U 方向闭合',
        type: 'boolean',
        defaultValue: false,
        dependsOn: 'mode',
        visibleWhenValues: ['parametric'],
      ),
      param(
        key: 'wrapColumns',
        label: 'V 方向闭合',
        type: 'boolean',
        defaultValue: false,
        dependsOn: 'mode',
        visibleWhenValues: ['parametric'],
      ),
      param(
        key: 'gridLayout',
        label: '表格布局',
        type: 'select',
        defaultValue: 'xyz',
        dependsOn: 'mode',
        visibleWhenValues: ['grid'],
        options: [
          {'value': 'xyz', 'label': '长表 X/Y/Z 列'},
          {'value': 'matrix', 'label': '二维矩阵'},
        ],
        help: '矩阵模式以第一列作为 Y 坐标，其余列名作为 X 坐标（非数字列名使用 0,1,…）。',
      ),
      param(
        key: 'xCol',
        label: '表格 X 列',
        type: 'text',
        defaultValue: 'x',
        dependsOn: 'mode',
        visibleWhenValues: ['grid'],
      ),
      param(
        key: 'yCol',
        label: '表格 Y 列',
        type: 'text',
        defaultValue: 'y',
        dependsOn: 'mode',
        visibleWhenValues: ['grid'],
      ),
      param(
        key: 'zCol',
        label: '表格 Z 列',
        type: 'text',
        defaultValue: 'z',
        dependsOn: 'mode',
        visibleWhenValues: ['grid'],
      ),
      param(
        key: 'valueCol',
        label: '外部标量列（可选）',
        type: 'text',
        defaultValue: '',
        dependsOn: 'mode',
        visibleWhenValues: ['grid'],
      ),
      param(
        key: 'size',
        label: '预设尺度',
        type: 'number',
        defaultValue: 2,
        min: 1e-12,
        step: 0.1,
        dependsOn: 'mode',
        visibleWhenValues: ['preset'],
      ),
      param(
        key: 'minorRadius',
        label: '环面小半径',
        type: 'number',
        defaultValue: 0.65,
        min: 1e-12,
        step: 0.1,
        dependsOn: 'mode',
        visibleWhenValues: ['preset'],
      ),
      param(
        key: 'constantZ',
        label: '平面/圆盘高度 Z',
        type: 'number',
        defaultValue: 0,
        step: 0.1,
        dependsOn: 'mode',
        visibleWhenValues: ['preset'],
      ),
      param(
        key: 'valueMode',
        label: '着色标量',
        type: 'select',
        defaultValue: 'z',
        options: [
          {'value': 'z', 'label': 'Z 值'},
          {'value': 'radius', 'label': '距原点距离'},
          {'value': 'none', 'label': '单色'},
        ],
      ),
      param(
        key: 'previewFaceBudget',
        label: '预览面预算',
        type: 'number',
        defaultValue: 6000,
        min: 100,
        max: 100000,
        step: 100,
      ),
      param(
        key: 'color',
        label: '面颜色',
        type: 'color',
        defaultValue: '',
        help: '单色模式或未连接色带时使用',
      ),
      param(
        key: 'opacity',
        label: '面不透明度',
        type: 'range',
        defaultValue: 0.6,
        min: 0.05,
        max: 1,
        step: 0.05,
      ),
      param(
        key: 'displayMode',
        label: '显示方式',
        type: 'select',
        defaultValue: 'surface',
        options: [
          {'value': 'surface', 'label': '实体曲面'},
          {'value': 'surfaceEdges', 'label': '实体 + 网格线'},
          {'value': 'wireframe', 'label': '仅网格线'},
        ],
        help: '合并原先互相冲突的线框、填充面和显示边缘线三个开关。',
      ),
      param(
        key: 'doubleSided',
        label: '双面显示',
        type: 'boolean',
        defaultValue: true,
        help: '关闭后按三角形绕序剔除背面。',
      ),
      param(
        key: 'edgeColor',
        label: '边缘线颜色',
        type: 'color',
        defaultValue: '',
        help: '留空时与面颜色一致',
      ),
    ],
    exec: kExec['surface_input'],
  ),
  NodeConfig(
    id: 'scatter_input',
    label: '点输入',
    category: Category.input,
    description: '逐个添加数据点:每个点可独立设置 X/Y 坐标、大小、形状与颜色。初始只有一个加号,可不断添加。',
    inputs: [],
    outputs: [s('out0', '散点', SocketType.scatter)],
    params: [
      param(key: 'name', label: '名称', type: 'text', defaultValue: '点输入'),
      param(
        key: 'points',
        label: '点输入列表',
        type: 'points',
        defaultValue: <PointInput>[],
        help: '点击"＋ 添加点"逐点添加;每个点有 x/y 坐标、大小、形状、颜色',
      ),
      ...pointStyleParams(),
    ],
    exec: kExec['scatter_input'],
  ),
  NodeConfig(
    id: 'func_curve',
    label: '曲线输入',
    category: Category.input,
    description:
        '输入曲线并采样输出:函数 y=f(x)、隐式方程 F(x,y)=0(圆/椭圆等全部 Desmos 曲线)、参数方程 x(t)/y(t)。支持 x/y/t、sin/cos/tan/exp/log/sqrt/abs、^、pi、e。',
    inputs: [],
    outputs: [s('out0', '曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '曲线名称', type: 'text', defaultValue: '曲线'),
      param(
        key: 'mode',
        label: '输入方式',
        type: 'select',
        defaultValue: 'function',
        options: [
          {'value': 'function', 'label': '函数 y=f(x)'},
          {'value': 'implicit', 'label': '隐式方程 F(x,y)=0'},
          {'value': 'parametric', 'label': '参数方程'},
        ],
      ),
      param(
        key: 'expression',
        label: '表达式',
        type: 'text',
        defaultValue: 'sin(x)',
        help: '函数:y=f(x),如 sin(x);隐式:F(x,y)=0,如 x^2+y^2-25',
        dependsOn: 'mode',
        visibleWhenValues: ['function', 'implicit'],
      ),
      param(
        key: 'exprX',
        label: 'x(t) 参数式',
        type: 'text',
        defaultValue: '3*cos(t)',
        help: '参数方程模式的 x(t),如 3*cos(t)',
        dependsOn: 'mode',
        visibleWhenValues: ['parametric'],
      ),
      param(
        key: 'exprY',
        label: 'y(t) 参数式',
        type: 'text',
        defaultValue: '2*sin(t)',
        help: '参数方程模式的 y(t),如 2*sin(t)',
        dependsOn: 'mode',
        visibleWhenValues: ['parametric'],
      ),
      param(
        key: 'xMin',
        label: 'X 起始',
        type: 'number',
        defaultValue: 0,
        step: 0.1,
      ),
      param(
        key: 'xMax',
        label: 'X 结束',
        type: 'number',
        defaultValue: 10,
        step: 0.1,
      ),
      param(
        key: 'yMin',
        label: 'Y 起始',
        type: 'number',
        defaultValue: -5,
        step: 0.1,
        help: '隐式方程模式的 Y 范围起始',
        dependsOn: 'mode',
        visibleWhenValues: ['implicit'],
      ),
      param(
        key: 'yMax',
        label: 'Y 结束',
        type: 'number',
        defaultValue: 5,
        step: 0.1,
        help: '隐式方程模式的 Y 范围结束',
        dependsOn: 'mode',
        visibleWhenValues: ['implicit'],
      ),
      param(
        key: 'samples',
        label: '采样数',
        type: 'number',
        defaultValue: 200,
        step: 1,
        min: 2,
      ),
      ...lineStyleParams(),
    ],
    exec: kExec['func_curve'],
  ),

  // ================= 数据初步节点 =================
  NodeConfig(
    id: 'clean',
    label: '数据清洗',
    category: Category.clean,
    description: '清理表格:缺失值填充(零/均值/线性插值)、删除含缺失的行、去除重复行。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '清洗后表格', SocketType.table)],
    params: [
      param(
        key: 'fillMissing',
        label: '缺失值填充',
        type: 'select',
        defaultValue: 'none',
        options: [
          {'value': 'none', 'label': '不填充'},
          {'value': 'zero', 'label': '填充 0'},
          {'value': 'mean', 'label': '填充均值'},
          {'value': 'interp', 'label': '线性插值'},
        ],
      ),
      param(
        key: 'dropMissing',
        label: '删除含缺失的行',
        type: 'boolean',
        defaultValue: false,
      ),
      param(
        key: 'dedupe',
        label: '去除重复行',
        type: 'boolean',
        defaultValue: false,
      ),
    ],
    exec: kExec['clean'],
  ),
  NodeConfig(
    id: 'normalize',
    label: '标准化',
    category: Category.clean,
    description: '对数值列做 min-max 归一化或 z-score 标准化。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '标准化表格', SocketType.table)],
    params: [
      param(
        key: 'method',
        label: '方法',
        type: 'select',
        defaultValue: 'minmax',
        options: [
          {'value': 'minmax', 'label': 'min-max 归一化'},
          {'value': 'zscore', 'label': 'z-score 标准化'},
        ],
      ),
      param(
        key: 'columns',
        label: '列(留空=全部数值列)',
        type: 'text',
        defaultValue: '',
        placeholder: '如:log2FC,pvalue 或 1,2',
      ),
    ],
    exec: kExec['normalize'],
  ),
  NodeConfig(
    id: 'filter',
    label: '条件筛选',
    category: Category.clean,
    description: '按某列数值区间筛选行(可剔除离群点)。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '筛选后表格', SocketType.table)],
    params: [
      param(key: 'column', label: '筛选列', type: 'text', defaultValue: ''),
      param(key: 'min', label: '最小值(留空不限)', type: 'text', defaultValue: ''),
      param(key: 'max', label: '最大值(留空不限)', type: 'text', defaultValue: ''),
    ],
    exec: kExec['filter'],
  ),
  NodeConfig(
    id: 'sample',
    label: '数据抽样',
    category: Category.clean,
    description: '对表格抽样:取前 N 行、隔行抽样或随机抽样。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '抽样表格', SocketType.table)],
    params: [
      param(
        key: 'method',
        label: '方法',
        type: 'select',
        defaultValue: 'first',
        options: [
          {'value': 'first', 'label': '取前 N 行'},
          {'value': 'every', 'label': '隔行抽样'},
          {'value': 'random', 'label': '随机抽样'},
        ],
      ),
      param(
        key: 'count',
        label: '行数(N)',
        type: 'number',
        defaultValue: 20,
        step: 1,
        min: 0,
      ),
      param(
        key: 'step',
        label: '步长(隔行)',
        type: 'number',
        defaultValue: 2,
        step: 1,
        min: 1,
      ),
      param(
        key: 'seed',
        label: '随机种子',
        type: 'number',
        defaultValue: 0,
        step: 1,
      ),
    ],
    exec: kExec['sample'],
  ),

  // ================= 数据运算节点 =================
  NodeConfig(
    id: 'derivative',
    label: '数值求导',
    category: Category.compute,
    description: '对曲线做数值求导(中心差分),输出导数曲线。',
    inputs: [s('in0', '曲线', SocketType.series)],
    outputs: [s('out0', '导数曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '导数'),
      ...lineStyleParams(),
    ],
    exec: kExec['derivative'],
  ),
  NodeConfig(
    id: 'integral',
    label: '数值积分',
    category: Category.compute,
    description: '对曲线做梯形法累积积分,输出积分曲线。',
    inputs: [s('in0', '曲线', SocketType.series)],
    outputs: [s('out0', '积分曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '积分'),
      ...lineStyleParams(),
    ],
    exec: kExec['integral'],
  ),
  NodeConfig(
    id: 'fit',
    label: '曲线拟合',
    category: Category.compute,
    description: '对散点做多项式(1~3 阶)或指数拟合,输出拟合曲线与系数表。',
    inputs: [s('in0', '散点', SocketType.scatter)],
    outputs: [
      s('out0', '拟合曲线', SocketType.series),
      s('out1', '系数表', SocketType.table),
    ],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '拟合曲线'),
      param(
        key: 'method',
        label: '方法',
        type: 'select',
        defaultValue: 'linear',
        options: [
          {'value': 'linear', 'label': '线性拟合'},
          {'value': 'poly', 'label': '多项式拟合'},
          {'value': 'exponential', 'label': '指数拟合'},
        ],
      ),
      param(
        key: 'degree',
        label: '多项式阶数',
        type: 'number',
        defaultValue: 2,
        step: 1,
        min: 1,
        max: 6,
      ),
      ...lineStyleParams(),
    ],
    exec: kExec['fit'],
  ),
  NodeConfig(
    id: 'smooth',
    label: '平滑',
    category: Category.compute,
    description: '滑动平均平滑曲线。',
    inputs: [s('in0', '曲线', SocketType.series)],
    outputs: [s('out0', '平滑曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '平滑曲线'),
      param(
        key: 'window',
        label: '窗口半径',
        type: 'number',
        defaultValue: 5,
        step: 1,
        min: 1,
      ),
      ...lineStyleParams(),
    ],
    exec: kExec['smooth'],
  ),
  NodeConfig(
    id: 'formula',
    label: '公式运算',
    category: Category.compute,
    description: '对曲线逐点计算 y\' = f(x),x 为原 x,y 为原 y。',
    inputs: [s('in0', '曲线', SocketType.series)],
    outputs: [s('out0', '结果曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '结果'),
      param(
        key: 'expression',
        label: '表达式 f(x)',
        type: 'text',
        defaultValue: '2*x + 1',
        help: '支持 x、y、sin/cos/exp/log/sqrt、^',
      ),
      ...lineStyleParams(),
    ],
    exec: kExec['formula'],
  ),
  NodeConfig(
    id: 'geometry_intersect',
    label: '线面求交',
    category: Category.compute,
    description: '支持曲线-曲线、曲线-曲面和曲面-曲面求交。交点由散点输出，面面交线由曲线输出。',
    inputs: [
      s('in0', '曲线/曲面 A', SocketType.any),
      s('in1', '曲线/曲面 B', SocketType.any),
    ],
    outputs: [
      s('out0', '交点', SocketType.scatter),
      s('out1', '交线', SocketType.series),
    ],
    params: [
      param(key: 'name', label: '输出名称', type: 'text', defaultValue: '交点'),
      ...pointStyleParams(),
      param(key: 'curveName', label: '交线名称', type: 'text', defaultValue: '交线'),
      ...lineStyleParams(),
    ],
    exec: kExec['geometry_intersect'],
  ),
  NodeConfig(
    id: 'stat_uncertainty',
    label: '误差与区间',
    category: Category.compute,
    description: '从表格构建带对称/非对称 X/Y 误差条或置信区间、预测区间带的曲线，并保存统计来源元数据。',
    inputs: [s('in0', '统计表格', SocketType.table)],
    outputs: [s('out0', '统计曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '名称', type: 'text', defaultValue: '统计曲线'),
      param(key: 'xCol', label: 'X 列', type: 'text', defaultValue: 'x'),
      param(key: 'yCol', label: 'Y 列', type: 'text', defaultValue: 'y'),
      param(key: 'xMinusCol', label: 'X 负误差列', type: 'text', defaultValue: ''),
      param(key: 'xPlusCol', label: 'X 正误差列', type: 'text', defaultValue: ''),
      param(
        key: 'yMinusCol',
        label: 'Y 负误差/下界列',
        type: 'text',
        defaultValue: '',
      ),
      param(
        key: 'yPlusCol',
        label: 'Y 正误差/上界列',
        type: 'text',
        defaultValue: '',
      ),
      param(
        key: 'representation',
        label: '表达方式',
        type: 'select',
        defaultValue: 'error',
        options: [
          {'value': 'error', 'label': '误差条（列为误差量）'},
          {'value': 'band', 'label': '区间带（Y 列为上下界）'},
        ],
      ),
      param(
        key: 'uncertaintyKind',
        label: '统计含义',
        type: 'select',
        defaultValue: 'sd',
        options: [
          {'value': 'sd', 'label': '标准差 SD'},
          {'value': 'se', 'label': '标准误 SE'},
          {'value': 'ci', 'label': '置信区间 CI'},
          {'value': 'pi', 'label': '预测区间 PI'},
          {'value': 'custom', 'label': '自定义'},
        ],
      ),
      param(key: 'source', label: '统计来源/方法', type: 'text', defaultValue: ''),
      ...lineStyleParams(),
    ],
    exec: kExec['stat_uncertainty'],
  ),

  // ================= 数据转化节点 =================
  NodeConfig(
    id: 'extract_columns',
    label: '提取列',
    category: Category.transform,
    description: '按列名或 1 起始索引提取表格列。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '新表格', SocketType.table)],
    params: [
      param(
        key: 'columns',
        label: '列(逗号分隔)',
        type: 'text',
        defaultValue: '',
        placeholder: '如:log2FC,pvalue 或 2,4',
      ),
    ],
    exec: kExec['extract_columns'],
  ),
  NodeConfig(
    id: 'extract_rows',
    label: '提取行',
    category: Category.transform,
    description: '按行区间与步长提取表格子集。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '新表格', SocketType.table)],
    params: [
      param(
        key: 'start',
        label: '起始行(0 起始)',
        type: 'number',
        defaultValue: 0,
        step: 1,
        min: 0,
      ),
      param(
        key: 'end',
        label: '结束行',
        type: 'number',
        defaultValue: 99,
        step: 1,
        min: 0,
      ),
      param(
        key: 'step',
        label: '步长',
        type: 'number',
        defaultValue: 1,
        step: 1,
        min: 1,
      ),
    ],
    exec: kExec['extract_rows'],
  ),
  NodeConfig(
    id: 'scatter_to_table',
    label: '散点转表格',
    category: Category.transform,
    description: '把散点转换为表格(列:x、y,含三维时为 x、y、z),便于输出、清洗或继续处理。',
    inputs: [s('in0', '散点', SocketType.scatter)],
    outputs: [s('out0', '表格', SocketType.table)],
    params: [],
    exec: kExec['scatter_to_table'],
  ),
  NodeConfig(
    id: 'table_to_scatter',
    label: '表格转散点',
    category: Category.transform,
    description:
        '选取表格中两(三)列生成散点,并携带点形状/大小/颜色。点大小与点颜色可暴露为输入口,接入数据列后每个点的大小/颜色与该行数值成正比。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '散点', SocketType.scatter)],
    params: [
      param(key: 'name', label: '名称', type: 'text', defaultValue: '散点'),
      param(key: 'xCol', label: 'X 列', type: 'text', defaultValue: ''),
      param(key: 'yCol', label: 'Y 列', type: 'text', defaultValue: ''),
      param(key: 'zCol', label: 'Z 列(可选,三维)', type: 'text', defaultValue: ''),
      param(
        key: 'pointShape',
        label: '点形状',
        type: 'select',
        defaultValue: 'circle',
        options: kShapeOptions,
      ),
      param(
        key: 'pointSize',
        label: '点大小',
        type: 'range',
        defaultValue: 4,
        min: 1,
        max: 16,
        step: 0.5,
        expose: true,
      ),
      param(
        key: 'pointColor',
        label: '点颜色',
        type: 'color',
        defaultValue: '#1f77b4',
        expose: true,
      ),
    ],
    exec: kExec['table_to_scatter'],
  ),
  NodeConfig(
    id: 'table_to_series',
    label: '表格转曲线',
    category: Category.transform,
    description: '选取表格中两列生成曲线,并携带线形状/粗细/颜色。线宽与线颜色可暴露为输入口,接入数据列后逐段变化。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [s('out0', '曲线', SocketType.series)],
    params: [
      param(key: 'name', label: '名称', type: 'text', defaultValue: '曲线'),
      param(key: 'xCol', label: 'X 列', type: 'text', defaultValue: ''),
      param(key: 'yCol', label: 'Y 列', type: 'text', defaultValue: ''),
      param(
        key: 'lineStyle',
        label: '线形状',
        type: 'select',
        defaultValue: 'solid',
        options: [
          {'value': 'solid', 'label': '实线'},
          {'value': 'dashed', 'label': '虚线'},
        ],
      ),
      param(
        key: 'lineWidth',
        label: '线宽',
        type: 'range',
        defaultValue: 2,
        min: 0.5,
        max: 10,
        step: 0.5,
        expose: true,
      ),
      param(
        key: 'lineColor',
        label: '线颜色',
        type: 'color',
        defaultValue: '#ff7f0e',
        expose: true,
      ),
    ],
    exec: kExec['table_to_series'],
  ),
  NodeConfig(
    id: 'series_to_scatter',
    label: '曲线转散点',
    category: Category.transform,
    description: '将曲线数据转化为散点数据,并携带点形状/大小/颜色。点大小与点颜色可暴露为输入口,接入数据列后逐点变化。',
    inputs: [s('in0', '曲线', SocketType.series)],
    outputs: [s('out0', '散点', SocketType.scatter)],
    params: [
      param(key: 'name', label: '名称', type: 'text', defaultValue: '散点'),
      param(
        key: 'pointShape',
        label: '点形状',
        type: 'select',
        defaultValue: 'circle',
        options: kShapeOptions,
      ),
      param(
        key: 'pointSize',
        label: '点大小',
        type: 'range',
        defaultValue: 4,
        min: 1,
        max: 16,
        step: 0.5,
        expose: true,
      ),
      param(
        key: 'pointColor',
        label: '点颜色',
        type: 'color',
        defaultValue: '#1f77b4',
        expose: true,
      ),
    ],
    exec: kExec['series_to_scatter'],
  ),

  // ================= 数据可视化节点 =================
  NodeConfig(
    id: 'viz_scatter',
    label: '散点图',
    category: Category.visualize,
    description: '以表格两列绘制散点图;也可直接接入散点/曲线数据可视化。',
    inputs: [s('in0', '表格', SocketType.table), ...kOverlaySockets],
    outputs: [],
    params: [
      param(
        key: 'xCol',
        label: 'X 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(
        key: 'yCol',
        label: 'Y 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
      param(
        key: 'fontSizeCm',
        label: '文字大小(厘米)',
        type: 'number',
        defaultValue: 0.28,
        min: 0.08,
        max: 2.0,
        step: 0.02,
        help: '图表文字尺寸,单位厘米(96dpi);与导出像素大小互相独立',
      ),
      param(
        key: 'canvasPxW',
        label: '导出像素宽度',
        type: 'number',
        defaultValue: 1920,
        min: 320,
        max: 8000,
        step: 10,
        help: 'PNG 导出像素宽度,高度按预览等比例;不影响任何区域的视觉比例',
      ),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_line',
    label: '折线图',
    category: Category.visualize,
    description: '以表格一列(或多条曲线)绘制折线图。',
    inputs: [s('in0', '表格', SocketType.table), ...kOverlaySockets],
    outputs: [],
    params: [
      param(
        key: 'xCol',
        label: 'X 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(
        key: 'yCol',
        label: 'Y 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
      param(
        key: 'fontSizeCm',
        label: '文字大小(厘米)',
        type: 'number',
        defaultValue: 0.28,
        min: 0.08,
        max: 2.0,
        step: 0.02,
        help: '图表文字尺寸,单位厘米(96dpi);与导出像素大小互相独立',
      ),
      param(
        key: 'canvasPxW',
        label: '导出像素宽度',
        type: 'number',
        defaultValue: 1920,
        min: 320,
        max: 8000,
        step: 10,
        help: 'PNG 导出像素宽度,高度按预览等比例;不影响任何区域的视觉比例',
      ),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_bar',
    label: '柱状图',
    category: Category.visualize,
    description: '以表格两列绘制柱状图(分类 + 数值)。',
    inputs: [s('in0', '表格', SocketType.table), ...kOverlaySockets],
    outputs: [],
    params: [
      param(
        key: 'xCol',
        label: 'X 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(
        key: 'yCol',
        label: 'Y 列',
        type: 'text',
        defaultValue: '',
        help: '留空自动选择',
      ),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
      param(
        key: 'fontSizeCm',
        label: '文字大小(厘米)',
        type: 'number',
        defaultValue: 0.28,
        min: 0.08,
        max: 2.0,
        step: 0.02,
        help: '图表文字尺寸,单位厘米(96dpi);与导出像素大小互相独立',
      ),
      param(
        key: 'canvasPxW',
        label: '导出像素宽度',
        type: 'number',
        defaultValue: 1920,
        min: 320,
        max: 8000,
        step: 10,
        help: 'PNG 导出像素宽度,高度按预览等比例;不影响任何区域的视觉比例',
      ),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_volcano',
    label: '火山图',
    category: Category.visualize,
    description: '差异分析火山图:以 log2FC 与 p 值两列绘制,自动标注显著点。可接入坐标系输入,按坐标系轴风格/范围/网格渲染。',
    inputs: [
      s('in0', '表格', SocketType.table),
      s('in1', '坐标系', SocketType.axes),
    ],
    outputs: [],
    params: [
      param(
        key: 'fcCol',
        label: 'log2FC 列',
        type: 'text',
        defaultValue: 'log2FC',
      ),
      param(key: 'pCol', label: 'p 值列', type: 'text', defaultValue: 'pvalue'),
      param(
        key: 'significanceKind',
        label: '显著性类型',
        type: 'select',
        defaultValue: 'p',
        options: const [
          {'value': 'p', 'label': 'p 值'},
          {'value': 'q', 'label': 'q 值/FDR'},
        ],
      ),
      param(
        key: 'fcThreshold',
        label: 'fold-change 阈值',
        type: 'number',
        defaultValue: 1.0,
        min: 0,
        step: 0.1,
      ),
      param(
        key: 'significanceThreshold',
        label: 'p/q 阈值',
        type: 'number',
        defaultValue: 0.05,
        min: 1e-300,
        max: 1,
        step: 0.01,
      ),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
      param(
        key: 'fontSizeCm',
        label: '文字大小(厘米)',
        type: 'number',
        defaultValue: 0.28,
        min: 0.08,
        max: 2.0,
        step: 0.02,
        help: '图表文字尺寸,单位厘米(96dpi);与导出像素大小互相独立',
      ),
      param(
        key: 'canvasPxW',
        label: '导出像素宽度',
        type: 'number',
        defaultValue: 1920,
        min: 320,
        max: 8000,
        step: 10,
        help: 'PNG 导出像素宽度,高度按预览等比例;不影响任何区域的视觉比例',
      ),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_heatmap',
    label: '热力图',
    category: Category.visualize,
    description: '数值矩阵热力图：显示全部数值列与行。可接入坐标系输入，按坐标系轴风格、范围与网格渲染；颜色渐变可在属性面板直接编辑。',
    inputs: [
      s('in0', '表格', SocketType.table),
      s('in1', '坐标系', SocketType.axes),
    ],
    outputs: [],
    params: [
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
      param(
        key: 'gradient',
        label: '颜色渐变',
        type: 'gradient',
        defaultValue: kDefaultGradient.map((s) => s.copy()).toList(),
        help: '热力图颜色映射渐变',
      ),
      param(
        key: 'fontSizeCm',
        label: '文字大小(厘米)',
        type: 'number',
        defaultValue: 0.28,
        min: 0.08,
        max: 2.0,
        step: 0.02,
        help: '图表文字尺寸,单位厘米(96dpi);与导出像素大小互相独立',
      ),
      param(
        key: 'canvasPxW',
        label: '导出像素宽度',
        type: 'number',
        defaultValue: 1920,
        min: 320,
        max: 8000,
        step: 10,
        help: 'PNG 导出像素宽度,高度按预览等比例;不影响任何区域的视觉比例',
      ),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_box',
    label: '箱线图',
    category: Category.visualize,
    description: '多组数值分布箱线图:每个数值列一个箱体。可接入坐标系输入,按坐标系轴风格/范围/网格渲染。',
    inputs: [
      s('in0', '表格', SocketType.table),
      s('in1', '坐标系', SocketType.axes),
    ],
    outputs: [],
    params: [
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
      param(
        key: 'whiskerMode',
        label: '须线模式',
        type: 'select',
        defaultValue: 'tukey',
        options: const [
          {'value': 'tukey', 'label': 'Tukey 1.5×IQR'},
          {'value': 'minmax', 'label': '最小值—最大值'},
        ],
      ),
      param(
        key: 'fontSizeCm',
        label: '文字大小(厘米)',
        type: 'number',
        defaultValue: 0.28,
        min: 0.08,
        max: 2.0,
        step: 0.02,
        help: '图表文字尺寸,单位厘米(96dpi);与导出像素大小互相独立',
      ),
      param(
        key: 'canvasPxW',
        label: '导出像素宽度',
        type: 'number',
        defaultValue: 1920,
        min: 320,
        max: 8000,
        step: 10,
        help: 'PNG 导出像素宽度,高度按预览等比例;不影响任何区域的视觉比例',
      ),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_violin',
    label: '小提琴图',
    category: Category.visualize,
    description: '多组数值分布小提琴图(核密度估计):每个数值列一个小提琴。可接入坐标系输入,按坐标系轴风格/范围/网格渲染。',
    inputs: [
      s('in0', '表格', SocketType.table),
      s('in1', '坐标系', SocketType.axes),
    ],
    outputs: [],
    params: [
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
      param(
        key: 'bandwidthMode',
        label: '带宽规则',
        type: 'select',
        defaultValue: 'silverman',
        options: const [
          {'value': 'silverman', 'label': 'Silverman'},
          {'value': 'scott', 'label': 'Scott'},
          {'value': 'manual', 'label': '手动'},
        ],
      ),
      param(
        key: 'bandwidth',
        label: '手动带宽/规则倍率',
        type: 'number',
        defaultValue: 1.0,
        min: 1e-12,
        step: 0.1,
      ),
      param(
        key: 'fontSizeCm',
        label: '文字大小(厘米)',
        type: 'number',
        defaultValue: 0.28,
        min: 0.08,
        max: 2.0,
        step: 0.02,
        help: '图表文字尺寸,单位厘米(96dpi);与导出像素大小互相独立',
      ),
      param(
        key: 'canvasPxW',
        label: '导出像素宽度',
        type: 'number',
        defaultValue: 1920,
        min: 320,
        max: 8000,
        step: 10,
        help: 'PNG 导出像素宽度,高度按预览等比例;不影响任何区域的视觉比例',
      ),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_sankey',
    label: '桑基图',
    category: Category.visualize,
    description: '流程/流量桑基图:按源列→目标列聚合权重。可接入坐标系输入,按坐标系轴风格/范围渲染;颜色渐变在属性面板编辑。',
    inputs: [
      s('in0', '表格', SocketType.table),
      s('in1', '坐标系', SocketType.axes),
    ],
    outputs: [],
    params: [
      param(
        key: 'sourceCol',
        label: '源列',
        type: 'text',
        defaultValue: '',
        help: '起点列',
      ),
      param(
        key: 'targetCol',
        label: '目标列',
        type: 'text',
        defaultValue: '',
        help: '终点列',
      ),
      param(
        key: 'valueCol',
        label: '权重列(可选)',
        type: 'text',
        defaultValue: '',
        help: '留空按出现次数',
      ),
      param(
        key: 'layout',
        label: '布局形态',
        type: 'select',
        defaultValue: 'linear',
        options: [
          {'value': 'linear', 'label': '直线型(左右分栏)'},
          {'value': 'circular', 'label': '环形(圆环辐射)'},
        ],
      ),
      param(
        key: 'labelDir',
        label: '标签排列',
        type: 'select',
        defaultValue: 'horizontal',
        options: [
          {'value': 'horizontal', 'label': '横排'},
          {'value': 'vertical', 'label': '竖排'},
          {'value': 'slant', 'label': '倾斜 45°'},
        ],
        help: '全部标签统一使用该排列方式(不使用 90° 旋转)',
      ),
      param(
        key: 'linkOpacity',
        label: '连接带透明度',
        type: 'range',
        defaultValue: 0.45,
        min: 0.05,
        max: 1.0,
        step: 0.05,
        help: '图中部连接带(连线色带)的不透明度',
      ),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
      param(
        key: 'fontSizeCm',
        label: '文字大小(厘米)',
        type: 'number',
        defaultValue: 0.28,
        min: 0.08,
        max: 2.0,
        step: 0.02,
        help: '图表文字尺寸,单位厘米(96dpi);与导出像素大小互相独立',
      ),
      param(
        key: 'canvasPxW',
        label: '导出像素宽度',
        type: 'number',
        defaultValue: 1920,
        min: 320,
        max: 8000,
        step: 10,
        help: 'PNG 导出像素宽度,高度按预览等比例;不影响任何区域的视觉比例',
      ),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_graph',
    label: '网络示意图',
    category: Category.visualize,
    description: '关系网络图(力导向布局):按源列→目标列构建边。可接入坐标系输入,按坐标系轴风格/范围渲染。',
    inputs: [
      s('in0', '表格', SocketType.table),
      s('in1', '坐标系', SocketType.axes),
    ],
    outputs: [],
    params: [
      param(
        key: 'sourceCol',
        label: '源列',
        type: 'text',
        defaultValue: '',
        help: '起点列',
      ),
      param(
        key: 'targetCol',
        label: '目标列',
        type: 'text',
        defaultValue: '',
        help: '终点列',
      ),
      param(
        key: 'valueCol',
        label: '权重列(可选)',
        type: 'text',
        defaultValue: '',
        help: '留空按出现次数',
      ),
      param(key: 'title', label: '图表标题', type: 'text', defaultValue: ''),
      param(
        key: 'fontSizeCm',
        label: '文字大小(厘米)',
        type: 'number',
        defaultValue: 0.28,
        min: 0.08,
        max: 2.0,
        step: 0.02,
        help: '图表文字尺寸,单位厘米(96dpi);与导出像素大小互相独立',
      ),
      param(
        key: 'canvasPxW',
        label: '导出像素宽度',
        type: 'number',
        defaultValue: 1920,
        min: 320,
        max: 8000,
        step: 10,
        help: 'PNG 导出像素宽度,高度按预览等比例;不影响任何区域的视觉比例',
      ),
    ],
    isViewer: true,
  ),
  NodeConfig(
    id: 'viz_principled',
    label: '原理化输出',
    category: Category.visualize,
    description:
        '只接受一个坐标系输入(坐标系本身携带轴属性、点/线/面/分布/文本图元与场景外观),本节点仅负责把坐标系的内容实例化渲染出来。',
    inputs: [s('in0', '坐标系', SocketType.axes)],
    outputs: [],
    params: [],
    isViewer: true,
  ),
  NodeConfig(
    id: 'data_output',
    label: '数据输出',
    category: Category.visualize,
    description: '输出节点:显示传入表格数据的预览(列名 + 前若干行),便于检查流水线中间结果。',
    inputs: [s('in0', '表格', SocketType.table)],
    outputs: [],
    params: [
      param(
        key: 'maxRows',
        label: '预览行数',
        type: 'number',
        defaultValue: 8,
        step: 1,
        min: 1,
        max: 50,
      ),
    ],
    isViewer: true,
  ),
];

final Map<String, NodeConfig> _configMap = {
  for (final c in kNodeConfigs) c.id: c,
};

NodeConfig? getConfig(String id) => _configMap[id];

List<NodeConfig> nodesByCategory(Category cat) =>
    kNodeConfigs.where((c) => c.category == cat).toList();

/// 数据类型自动转换表:(源类型, 目标类型) → 转换节点 configId。
/// Alt 拖拽连线到不可直接相连但可转换的端口时,自动在路径中点插入转换节点;
/// 一条转换可多步串联(如 曲线→表格 = 曲线转散点→散点转表格)。
const Map<({SocketType from, SocketType to}), String> kTypeConversions = {
  (from: SocketType.table, to: SocketType.scatter): 'table_to_scatter',
  (from: SocketType.table, to: SocketType.series): 'table_to_series',
  (from: SocketType.series, to: SocketType.scatter): 'series_to_scatter',
  (from: SocketType.scatter, to: SocketType.table): 'scatter_to_table',
};

/// 转换邻接表:类型 → 一步转换可达的 (目标类型, 转换节点 configId)
final Map<SocketType, List<({SocketType to, String configId})>> _conversionAdj =
    () {
      final m = <SocketType, List<({SocketType to, String configId})>>{};
      for (final e in kTypeConversions.entries) {
        m.putIfAbsent(e.key.from, () => []).add((
          to: e.key.to,
          configId: e.value,
        ));
      }
      return m;
    }();

/// 查询 from→to 的最短转换链(BFS,允许多步,如 曲线→表格):
/// 返回依次执行的转换节点 configId 列表;from==to 或不可转换时返回 null。
List<String>? conversionPath(SocketType from, SocketType to) {
  if (from == to) return null;
  if (_conversionAdj[from] == null) return null;
  // prev[t] = (上一步类型, 这一步用的转换节点);visied 去重防环
  final prev = <SocketType, ({SocketType from, String configId})>{};
  final visited = <SocketType>{from};
  final queue = <SocketType>[from];
  while (queue.isNotEmpty) {
    final cur = queue.removeAt(0);
    for (final e
        in _conversionAdj[cur] ??
            const <({SocketType to, String configId})>[]) {
      if (visited.contains(e.to)) continue;
      visited.add(e.to);
      prev[e.to] = (from: cur, configId: e.configId);
      if (e.to == to) {
        // 回溯最短路径
        final path = <String>[e.configId];
        var p = cur;
        while (p != from) {
          final back = prev[p]!;
          path.insert(0, back.configId);
          p = back.from;
        }
        return path;
      }
      queue.add(e.to);
    }
  }
  return null;
}
